// Code generated by protoc-gen-go-plugin. DO NOT EDIT.
// versions:
// 	protoc-gen-go-plugin v0.1.0
// 	protoc               v5.29.3
// source: pkg/plugin/sdk/servers/servers.proto

package servers

import (
	context "context"
	common "github.com/gameap/gameap/pkg/plugin/sdk/common"
	proto "github.com/gameap/gameap/pkg/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FindServersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filter     *ServerFilter      `protobuf:"bytes,1,opt,name=filter,proto3,oneof" json:"filter,omitempty"`
	Sorting    []*common.Sorting  `protobuf:"bytes,2,rep,name=sorting,proto3" json:"sorting,omitempty"`
	Pagination *common.Pagination `protobuf:"bytes,3,opt,name=pagination,proto3,oneof" json:"pagination,omitempty"`
}

func (x *FindServersRequest) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *FindServersRequest) GetFilter() *ServerFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *FindServersRequest) GetSorting() []*common.Sorting {
	if x != nil {
		return x.Sorting
	}
	return nil
}

func (x *FindServersRequest) GetPagination() *common.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ServerFilter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ids           []uint64                     `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	NodeIds       []uint64                     `protobuf:"varint,2,rep,packed,name=node_ids,json=nodeIds,proto3" json:"node_ids,omitempty"`
	GameIds       []string                     `protobuf:"bytes,3,rep,name=game_ids,json=gameIds,proto3" json:"game_ids,omitempty"`
	Enabled       *bool                        `protobuf:"varint,4,opt,name=enabled,proto3,oneof" json:"enabled,omitempty"`
	ProcessActive *bool                        `protobuf:"varint,5,opt,name=process_active,json=processActive,proto3,oneof" json:"process_active,omitempty"`
	Installed     *proto.ServerInstalledStatus `protobuf:"varint,6,opt,name=installed,proto3,enum=gameap.ServerInstalledStatus,oneof" json:"installed,omitempty"`
}

func (x *ServerFilter) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *ServerFilter) GetIds() []uint64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *ServerFilter) GetNodeIds() []uint64 {
	if x != nil {
		return x.NodeIds
	}
	return nil
}

func (x *ServerFilter) GetGameIds() []string {
	if x != nil {
		return x.GameIds
	}
	return nil
}

func (x *ServerFilter) GetEnabled() bool {
	if x != nil && x.Enabled != nil {
		return *x.Enabled
	}
	return false
}

func (x *ServerFilter) GetProcessActive() bool {
	if x != nil && x.ProcessActive != nil {
		return *x.ProcessActive
	}
	return false
}

func (x *ServerFilter) GetInstalled() proto.ServerInstalledStatus {
	if x != nil && x.Installed != nil {
		return *x.Installed
	}
	return proto.ServerInstalledStatus_SERVER_INSTALLED_STATUS_NOT_INSTALLED
}

type FindServersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Servers []*proto.Server `protobuf:"bytes,1,rep,name=servers,proto3" json:"servers,omitempty"`
	Total   int32           `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *FindServersResponse) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *FindServersResponse) GetServers() []*proto.Server {
	if x != nil {
		return x.Servers
	}
	return nil
}

func (x *FindServersResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetServerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetServerRequest) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *GetServerRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetServerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Server *proto.Server `protobuf:"bytes,1,opt,name=server,proto3,oneof" json:"server,omitempty"`
	Found  bool          `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
}

func (x *GetServerResponse) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *GetServerResponse) GetServer() *proto.Server {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *GetServerResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type SaveServerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Server *proto.Server `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
}

func (x *SaveServerRequest) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *SaveServerRequest) GetServer() *proto.Server {
	if x != nil {
		return x.Server
	}
	return nil
}

type SaveServerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool    `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error   *string `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error,omitempty"`
	Id      uint64  `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *SaveServerResponse) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *SaveServerResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SaveServerResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

func (x *SaveServerResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteServerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteServerRequest) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *DeleteServerRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteServerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool    `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error   *string `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error,omitempty"`
}

func (x *DeleteServerResponse) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *DeleteServerResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteServerResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

// ServersService provides server repository access to plugins
// go:plugin type=host module=gameap-servers
type ServersService interface {
	FindServers(context.Context, *FindServersRequest) (*FindServersResponse, error)
	GetServer(context.Context, *GetServerRequest) (*GetServerResponse, error)
	SaveServer(context.Context, *SaveServerRequest) (*SaveServerResponse, error)
	DeleteServer(context.Context, *DeleteServerRequest) (*DeleteServerResponse, error)
}
