// Code generated by protoc-gen-go-plugin. DO NOT EDIT.
// versions:
// 	protoc-gen-go-plugin v0.1.0
// 	protoc               v5.29.3
// source: pkg/plugin/sdk/servercontrol/servercontrol.proto

package servercontrol

import (
	context "context"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServerControlRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerId uint64 `protobuf:"varint,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
}

func (x *ServerControlRequest) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *ServerControlRequest) GetServerId() uint64 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

type ServerControlResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool    `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error   *string `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error,omitempty"`
	TaskId  *uint64 `protobuf:"varint,3,opt,name=task_id,json=taskId,proto3,oneof" json:"task_id,omitempty"`
}

func (x *ServerControlResponse) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *ServerControlResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ServerControlResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

func (x *ServerControlResponse) GetTaskId() uint64 {
	if x != nil && x.TaskId != nil {
		return *x.TaskId
	}
	return 0
}

// ServerControlService provides server control capabilities to plugins
// go:plugin type=host module=gameap-servercontrol
type ServerControlService interface {
	StartServer(context.Context, *ServerControlRequest) (*ServerControlResponse, error)
	StopServer(context.Context, *ServerControlRequest) (*ServerControlResponse, error)
	RestartServer(context.Context, *ServerControlRequest) (*ServerControlResponse, error)
	UpdateServer(context.Context, *ServerControlRequest) (*ServerControlResponse, error)
	InstallServer(context.Context, *ServerControlRequest) (*ServerControlResponse, error)
	ReinstallServer(context.Context, *ServerControlRequest) (*ServerControlResponse, error)
}
