export interface MockFile {
    path: string
    timestamp: number
    type: 'file' | 'dir'
    visibility: 'public' | 'private'
    size: number
    dirname: string
    basename: string
    extension?: string
    filename: string
    // Internal: file content for download/read
    _content?: string | ArrayBuffer
    _contentType?: 'text' | 'binary'
}

export interface MockDirectory {
    path: string
    timestamp: number
    type: 'dir'
    visibility: 'public' | 'private'
    dirname: string
    basename: string
}

// Create binary content (256 bytes: 0x00 to 0xFF)
function createBinaryContent(): ArrayBuffer {
    const buffer = new ArrayBuffer(256)
    const view = new Uint8Array(buffer)
    for (let i = 0; i < 256; i++) {
        view[i] = i
    }
    return buffer
}

// Create a more complex binary file (1KB with patterns)
function createComplexBinaryContent(): ArrayBuffer {
    const buffer = new ArrayBuffer(1024)
    const view = new Uint8Array(buffer)

    // Header pattern
    view[0] = 0x89
    view[1] = 0x50
    view[2] = 0x4E
    view[3] = 0x47 // PNG-like header

    // Fill rest with repeating pattern
    for (let i = 4; i < 1024; i++) {
        view[i] = (i * 7 + 13) % 256
    }
    return buffer
}

const now = Math.floor(Date.now() / 1000)

// Mock files in root directory
export const mockFiles: MockFile[] = [
    {
        path: 'server.properties',
        timestamp: now - 86400, // 1 day ago
        type: 'file',
        visibility: 'private',
        size: 512,
        dirname: '',
        basename: 'server.properties',
        extension: 'properties',
        filename: 'server',
        _contentType: 'text',
        _content: `# Minecraft server properties
# Generated by GameAP Debug Harness

server-port=25565
gamemode=survival
difficulty=normal
max-players=20
motd=A Minecraft Server
enable-command-block=false
spawn-protection=16
view-distance=10
online-mode=true
pvp=true
level-name=world
level-seed=
`,
    },
    {
        path: 'start.sh',
        timestamp: now - 172800, // 2 days ago
        type: 'file',
        visibility: 'public',
        size: 256,
        dirname: '',
        basename: 'start.sh',
        extension: 'sh',
        filename: 'start',
        _contentType: 'text',
        _content: `#!/bin/bash
# Server start script

java -Xmx2G -Xms1G -jar server.jar nogui
`,
    },
    {
        path: 'readme.txt',
        timestamp: now - 3600, // 1 hour ago
        type: 'file',
        visibility: 'private',
        size: 454,
        dirname: '',
        basename: 'readme.txt',
        extension: 'txt',
        filename: 'readme',
        _contentType: 'text',
        _content: `GameAP Debug Harness
====================

This is a sample text file for testing text editors.
You can edit this content and test the save functionality.

Line with special chars: <>&"'
Unicode: Hello, Мир!
`,
    },
    {
        path: 'server.jar',
        timestamp: now - 604800, // 1 week ago
        type: 'file',
        visibility: 'private',
        size: 11197597,
        dirname: '',
        basename: 'server.jar',
        extension: 'jar',
        filename: 'server',
        _contentType: 'binary',
        _content: createComplexBinaryContent(),
    },
    {
        path: 'backup.zip',
        timestamp: now - 7200, // 2 hours ago
        type: 'file',
        visibility: 'private',
        size: 27160,
        dirname: '',
        basename: 'backup.zip',
        extension: 'zip',
        filename: 'backup',
        _contentType: 'binary',
        _content: createBinaryContent(),
    },
]

// Mock directories
export const mockDirectories: MockDirectory[] = [
    {
        path: 'config',
        timestamp: now - 86400,
        type: 'dir',
        visibility: 'public',
        dirname: '',
        basename: 'config',
    },
    {
        path: 'logs',
        timestamp: now - 3600,
        type: 'dir',
        visibility: 'public',
        dirname: '',
        basename: 'logs',
    },
    {
        path: 'plugins',
        timestamp: now - 172800,
        type: 'dir',
        visibility: 'public',
        dirname: '',
        basename: 'plugins',
    },
    {
        path: 'world',
        timestamp: now - 43200,
        type: 'dir',
        visibility: 'public',
        dirname: '',
        basename: 'world',
    },
]

// Files in subdirectories
export const mockSubdirectoryFiles: Record<string, MockFile[]> = {
    'config': [
        {
            path: 'config/config.json',
            timestamp: now - 86400,
            type: 'file',
            visibility: 'private',
            size: 256,
            dirname: 'config',
            basename: 'config.json',
            extension: 'json',
            filename: 'config',
            _contentType: 'text',
            _content: JSON.stringify({
                version: '1.0.0',
                settings: {
                    debug: true,
                    logLevel: 'info',
                    maxConnections: 100,
                },
                features: {
                    autoSave: true,
                    compression: false,
                },
            }, null, 2),
        },
        {
            path: 'config/settings.yml',
            timestamp: now - 172800,
            type: 'file',
            visibility: 'private',
            size: 128,
            dirname: 'config',
            basename: 'settings.yml',
            extension: 'yml',
            filename: 'settings',
            _contentType: 'text',
            _content: `# Settings
server:
  name: "My Server"
  port: 25565
  max-players: 20
`,
        },
    ],
    'logs': [
        {
            path: 'logs/latest.log',
            timestamp: now - 60,
            type: 'file',
            visibility: 'private',
            size: 4096,
            dirname: 'logs',
            basename: 'latest.log',
            extension: 'log',
            filename: 'latest',
            _contentType: 'text',
            _content: `[12:00:00] [Server thread/INFO]: Starting server...
[12:00:01] [Server thread/INFO]: Loading properties
[12:00:02] [Server thread/INFO]: Starting Minecraft server on *:25565
[12:00:05] [Server thread/INFO]: Done (3.245s)! For help, type "help"
[12:01:00] [Server thread/INFO]: Player1 joined the game
[12:05:30] [Server thread/INFO]: Player1 left the game
`,
        },
    ],
    'plugins': [
        {
            path: 'plugins/example-plugin.jar',
            timestamp: now - 259200,
            type: 'file',
            visibility: 'private',
            size: 524288,
            dirname: 'plugins',
            basename: 'example-plugin.jar',
            extension: 'jar',
            filename: 'example-plugin',
            _contentType: 'binary',
            _content: createBinaryContent(),
        },
    ],
}

// Subdirectories in directories
export const mockSubdirectories: Record<string, MockDirectory[]> = {
    'config': [],
    'logs': [
        {
            path: 'logs/archive',
            timestamp: now - 604800,
            type: 'dir',
            visibility: 'public',
            dirname: 'logs',
            basename: 'archive',
        },
    ],
    'plugins': [],
    'world': [
        {
            path: 'world/region',
            timestamp: now - 43200,
            type: 'dir',
            visibility: 'public',
            dirname: 'world',
            basename: 'region',
        },
        {
            path: 'world/data',
            timestamp: now - 43200,
            type: 'dir',
            visibility: 'public',
            dirname: 'world',
            basename: 'data',
        },
    ],
}

export function getFileByPath(path: string): MockFile | undefined {
    // Check root files
    const rootFile = mockFiles.find(f => f.path === path)
    if (rootFile) return rootFile

    // Check subdirectory files
    for (const files of Object.values(mockSubdirectoryFiles)) {
        const file = files.find(f => f.path === path)
        if (file) return file
    }

    return undefined
}

export function getFileContent(file: MockFile): string | ArrayBuffer {
    return file._content || ''
}

export function getFileIcon(file: MockFile): string {
    if (file._contentType === 'binary') {
        return 'fa-solid fa-file-code'
    }

    switch (file.extension) {
        case 'json':
            return 'fa-solid fa-file-code'
        case 'cfg':
        case 'properties':
        case 'yml':
        case 'yaml':
            return 'fa-solid fa-file-lines'
        case 'txt':
        case 'log':
            return 'fa-solid fa-file'
        case 'jar':
        case 'zip':
            return 'fa-solid fa-file-zipper'
        case 'sh':
            return 'fa-solid fa-terminal'
        default:
            return 'fa-solid fa-file'
    }
}
