// Code generated by protoc-gen-go-plugin. DO NOT EDIT.
// versions:
// 	protoc-gen-go-plugin v0.1.0
// 	protoc               v5.29.3
// source: pkg/plugin/sdk/games/games.proto

package games

import (
	context "context"
	common "github.com/gameap/gameap/pkg/plugin/sdk/common"
	proto "github.com/gameap/gameap/pkg/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FindGamesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filter     *GameFilter        `protobuf:"bytes,1,opt,name=filter,proto3,oneof" json:"filter,omitempty"`
	Sorting    []*common.Sorting  `protobuf:"bytes,2,rep,name=sorting,proto3" json:"sorting,omitempty"`
	Pagination *common.Pagination `protobuf:"bytes,3,opt,name=pagination,proto3,oneof" json:"pagination,omitempty"`
}

func (x *FindGamesRequest) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *FindGamesRequest) GetFilter() *GameFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *FindGamesRequest) GetSorting() []*common.Sorting {
	if x != nil {
		return x.Sorting
	}
	return nil
}

func (x *FindGamesRequest) GetPagination() *common.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type GameFilter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Codes   []string `protobuf:"bytes,1,rep,name=codes,proto3" json:"codes,omitempty"`
	Engine  *string  `protobuf:"bytes,2,opt,name=engine,proto3,oneof" json:"engine,omitempty"`
	Enabled *bool    `protobuf:"varint,3,opt,name=enabled,proto3,oneof" json:"enabled,omitempty"`
}

func (x *GameFilter) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *GameFilter) GetCodes() []string {
	if x != nil {
		return x.Codes
	}
	return nil
}

func (x *GameFilter) GetEngine() string {
	if x != nil && x.Engine != nil {
		return *x.Engine
	}
	return ""
}

func (x *GameFilter) GetEnabled() bool {
	if x != nil && x.Enabled != nil {
		return *x.Enabled
	}
	return false
}

type FindGamesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Games []*proto.Game `protobuf:"bytes,1,rep,name=games,proto3" json:"games,omitempty"`
	Total int32         `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *FindGamesResponse) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *FindGamesResponse) GetGames() []*proto.Game {
	if x != nil {
		return x.Games
	}
	return nil
}

func (x *FindGamesResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetGameRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *GetGameRequest) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *GetGameRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type GetGameResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Game  *proto.Game `protobuf:"bytes,1,opt,name=game,proto3,oneof" json:"game,omitempty"`
	Found bool        `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
}

func (x *GetGameResponse) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *GetGameResponse) GetGame() *proto.Game {
	if x != nil {
		return x.Game
	}
	return nil
}

func (x *GetGameResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

// GamesService provides game repository access to plugins
// go:plugin type=host module=gameap-games
type GamesService interface {
	FindGames(context.Context, *FindGamesRequest) (*FindGamesResponse, error)
	GetGame(context.Context, *GetGameRequest) (*GetGameResponse, error)
}
