// Code generated by protoc-gen-go-plugin. DO NOT EDIT.
// versions:
// 	protoc-gen-go-plugin v0.1.0
// 	protoc               v5.29.3
// source: pkg/plugin/sdk/daemontasks/daemontasks.proto

package daemontasks

import (
	context "context"
	common "github.com/gameap/gameap/pkg/plugin/sdk/common"
	proto "github.com/gameap/gameap/pkg/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FindDaemonTasksRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filter     *DaemonTaskFilter  `protobuf:"bytes,1,opt,name=filter,proto3,oneof" json:"filter,omitempty"`
	Sorting    []*common.Sorting  `protobuf:"bytes,2,rep,name=sorting,proto3" json:"sorting,omitempty"`
	Pagination *common.Pagination `protobuf:"bytes,3,opt,name=pagination,proto3,oneof" json:"pagination,omitempty"`
}

func (x *FindDaemonTasksRequest) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *FindDaemonTasksRequest) GetFilter() *DaemonTaskFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *FindDaemonTasksRequest) GetSorting() []*common.Sorting {
	if x != nil {
		return x.Sorting
	}
	return nil
}

func (x *FindDaemonTasksRequest) GetPagination() *common.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type DaemonTaskFilter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ids       []uint64 `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	ServerIds []uint64 `protobuf:"varint,2,rep,packed,name=server_ids,json=serverIds,proto3" json:"server_ids,omitempty"`
	NodeIds   []uint64 `protobuf:"varint,3,rep,packed,name=node_ids,json=nodeIds,proto3" json:"node_ids,omitempty"`
	Statuses  []string `protobuf:"bytes,4,rep,name=statuses,proto3" json:"statuses,omitempty"`
	TaskTypes []string `protobuf:"bytes,5,rep,name=task_types,json=taskTypes,proto3" json:"task_types,omitempty"`
}

func (x *DaemonTaskFilter) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *DaemonTaskFilter) GetIds() []uint64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *DaemonTaskFilter) GetServerIds() []uint64 {
	if x != nil {
		return x.ServerIds
	}
	return nil
}

func (x *DaemonTaskFilter) GetNodeIds() []uint64 {
	if x != nil {
		return x.NodeIds
	}
	return nil
}

func (x *DaemonTaskFilter) GetStatuses() []string {
	if x != nil {
		return x.Statuses
	}
	return nil
}

func (x *DaemonTaskFilter) GetTaskTypes() []string {
	if x != nil {
		return x.TaskTypes
	}
	return nil
}

type FindDaemonTasksResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tasks []*proto.DaemonTask `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	Total int32               `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *FindDaemonTasksResponse) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *FindDaemonTasksResponse) GetTasks() []*proto.DaemonTask {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *FindDaemonTasksResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type CreateDaemonTaskRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeId     uint64  `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	ServerId   *uint64 `protobuf:"varint,2,opt,name=server_id,json=serverId,proto3,oneof" json:"server_id,omitempty"`
	TaskType   string  `protobuf:"bytes,3,opt,name=task_type,json=taskType,proto3" json:"task_type,omitempty"`
	Data       *string `protobuf:"bytes,4,opt,name=data,proto3,oneof" json:"data,omitempty"`
	Cmd        *string `protobuf:"bytes,5,opt,name=cmd,proto3,oneof" json:"cmd,omitempty"`
	RunAfterId *uint64 `protobuf:"varint,6,opt,name=run_after_id,json=runAfterId,proto3,oneof" json:"run_after_id,omitempty"`
}

func (x *CreateDaemonTaskRequest) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *CreateDaemonTaskRequest) GetNodeId() uint64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *CreateDaemonTaskRequest) GetServerId() uint64 {
	if x != nil && x.ServerId != nil {
		return *x.ServerId
	}
	return 0
}

func (x *CreateDaemonTaskRequest) GetTaskType() string {
	if x != nil {
		return x.TaskType
	}
	return ""
}

func (x *CreateDaemonTaskRequest) GetData() string {
	if x != nil && x.Data != nil {
		return *x.Data
	}
	return ""
}

func (x *CreateDaemonTaskRequest) GetCmd() string {
	if x != nil && x.Cmd != nil {
		return *x.Cmd
	}
	return ""
}

func (x *CreateDaemonTaskRequest) GetRunAfterId() uint64 {
	if x != nil && x.RunAfterId != nil {
		return *x.RunAfterId
	}
	return 0
}

type CreateDaemonTaskResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool    `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error   *string `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error,omitempty"`
	TaskId  uint64  `protobuf:"varint,3,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
}

func (x *CreateDaemonTaskResponse) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *CreateDaemonTaskResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateDaemonTaskResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

func (x *CreateDaemonTaskResponse) GetTaskId() uint64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

// DaemonTasksService provides daemon task repository access to plugins
// go:plugin type=host module=gameap-daemontasks
type DaemonTasksService interface {
	FindDaemonTasks(context.Context, *FindDaemonTasksRequest) (*FindDaemonTasksResponse, error)
	CreateDaemonTask(context.Context, *CreateDaemonTaskRequest) (*CreateDaemonTaskResponse, error)
}
