// Code generated by protoc-gen-go-plugin. DO NOT EDIT.
// versions:
// 	protoc-gen-go-plugin v0.1.0
// 	protoc               v5.29.3
// source: pkg/plugin/sdk/nodes/nodes.proto

package nodes

import (
	context "context"
	common "github.com/gameap/gameap/pkg/plugin/sdk/common"
	proto "github.com/gameap/gameap/pkg/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FindNodesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filter     *NodeFilter        `protobuf:"bytes,1,opt,name=filter,proto3,oneof" json:"filter,omitempty"`
	Sorting    []*common.Sorting  `protobuf:"bytes,2,rep,name=sorting,proto3" json:"sorting,omitempty"`
	Pagination *common.Pagination `protobuf:"bytes,3,opt,name=pagination,proto3,oneof" json:"pagination,omitempty"`
}

func (x *FindNodesRequest) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *FindNodesRequest) GetFilter() *NodeFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *FindNodesRequest) GetSorting() []*common.Sorting {
	if x != nil {
		return x.Sorting
	}
	return nil
}

func (x *FindNodesRequest) GetPagination() *common.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type NodeFilter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ids     []uint64 `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	Enabled *bool    `protobuf:"varint,2,opt,name=enabled,proto3,oneof" json:"enabled,omitempty"`
	Os      *string  `protobuf:"bytes,3,opt,name=os,proto3,oneof" json:"os,omitempty"`
}

func (x *NodeFilter) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *NodeFilter) GetIds() []uint64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *NodeFilter) GetEnabled() bool {
	if x != nil && x.Enabled != nil {
		return *x.Enabled
	}
	return false
}

func (x *NodeFilter) GetOs() string {
	if x != nil && x.Os != nil {
		return *x.Os
	}
	return ""
}

type FindNodesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nodes []*proto.Node `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Total int32         `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *FindNodesResponse) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *FindNodesResponse) GetNodes() []*proto.Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *FindNodesResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetNodeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetNodeRequest) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *GetNodeRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetNodeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Node  *proto.Node `protobuf:"bytes,1,opt,name=node,proto3,oneof" json:"node,omitempty"`
	Found bool        `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
}

func (x *GetNodeResponse) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *GetNodeResponse) GetNode() *proto.Node {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *GetNodeResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

// NodesService provides node repository access to plugins
// go:plugin type=host module=gameap-nodes
type NodesService interface {
	FindNodes(context.Context, *FindNodesRequest) (*FindNodesResponse, error)
	GetNode(context.Context, *GetNodeRequest) (*GetNodeResponse, error)
}
