// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: pkg/proto/entity.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EntityType int32

const (
	EntityType_ENTITY_TYPE_UNSPECIFIED        EntityType = 0
	EntityType_ENTITY_TYPE_USER               EntityType = 1
	EntityType_ENTITY_TYPE_NODE               EntityType = 2
	EntityType_ENTITY_TYPE_CLIENT_CERTIFICATE EntityType = 3
	EntityType_ENTITY_TYPE_GAME               EntityType = 4
	EntityType_ENTITY_TYPE_GAME_MOD           EntityType = 5
	EntityType_ENTITY_TYPE_SERVER             EntityType = 6
	EntityType_ENTITY_TYPE_ROLE               EntityType = 7
)

// Enum value maps for EntityType.
var (
	EntityType_name = map[int32]string{
		0: "ENTITY_TYPE_UNSPECIFIED",
		1: "ENTITY_TYPE_USER",
		2: "ENTITY_TYPE_NODE",
		3: "ENTITY_TYPE_CLIENT_CERTIFICATE",
		4: "ENTITY_TYPE_GAME",
		5: "ENTITY_TYPE_GAME_MOD",
		6: "ENTITY_TYPE_SERVER",
		7: "ENTITY_TYPE_ROLE",
	}
	EntityType_value = map[string]int32{
		"ENTITY_TYPE_UNSPECIFIED":        0,
		"ENTITY_TYPE_USER":               1,
		"ENTITY_TYPE_NODE":               2,
		"ENTITY_TYPE_CLIENT_CERTIFICATE": 3,
		"ENTITY_TYPE_GAME":               4,
		"ENTITY_TYPE_GAME_MOD":           5,
		"ENTITY_TYPE_SERVER":             6,
		"ENTITY_TYPE_ROLE":               7,
	}
)

func (x EntityType) Enum() *EntityType {
	p := new(EntityType)
	*p = x
	return p
}

func (x EntityType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EntityType) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_entity_proto_enumTypes[0].Descriptor()
}

func (EntityType) Type() protoreflect.EnumType {
	return &file_pkg_proto_entity_proto_enumTypes[0]
}

func (x EntityType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EntityType.Descriptor instead.
func (EntityType) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_entity_proto_rawDescGZIP(), []int{0}
}

var File_pkg_proto_entity_proto protoreflect.FileDescriptor

const file_pkg_proto_entity_proto_rawDesc = "" +
	"\n" +
	"\x16pkg/proto/entity.proto\x12\x06gameap*\xd7\x01\n" +
	"\n" +
	"EntityType\x12\x1b\n" +
	"\x17ENTITY_TYPE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10ENTITY_TYPE_USER\x10\x01\x12\x14\n" +
	"\x10ENTITY_TYPE_NODE\x10\x02\x12\"\n" +
	"\x1eENTITY_TYPE_CLIENT_CERTIFICATE\x10\x03\x12\x14\n" +
	"\x10ENTITY_TYPE_GAME\x10\x04\x12\x18\n" +
	"\x14ENTITY_TYPE_GAME_MOD\x10\x05\x12\x16\n" +
	"\x12ENTITY_TYPE_SERVER\x10\x06\x12\x14\n" +
	"\x10ENTITY_TYPE_ROLE\x10\aB$Z\"github.com/gameap/gameap/pkg/protob\x06proto3"

var (
	file_pkg_proto_entity_proto_rawDescOnce sync.Once
	file_pkg_proto_entity_proto_rawDescData []byte
)

func file_pkg_proto_entity_proto_rawDescGZIP() []byte {
	file_pkg_proto_entity_proto_rawDescOnce.Do(func() {
		file_pkg_proto_entity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_entity_proto_rawDesc), len(file_pkg_proto_entity_proto_rawDesc)))
	})
	return file_pkg_proto_entity_proto_rawDescData
}

var file_pkg_proto_entity_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_proto_entity_proto_goTypes = []any{
	(EntityType)(0), // 0: gameap.EntityType
}
var file_pkg_proto_entity_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_proto_entity_proto_init() }
func file_pkg_proto_entity_proto_init() {
	if File_pkg_proto_entity_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_entity_proto_rawDesc), len(file_pkg_proto_entity_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_proto_entity_proto_goTypes,
		DependencyIndexes: file_pkg_proto_entity_proto_depIdxs,
		EnumInfos:         file_pkg_proto_entity_proto_enumTypes,
	}.Build()
	File_pkg_proto_entity_proto = out.File
	file_pkg_proto_entity_proto_goTypes = nil
	file_pkg_proto_entity_proto_depIdxs = nil
}
