// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: game.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Game struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Code                    string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Name                    string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Engine                  string                 `protobuf:"bytes,3,opt,name=engine,proto3" json:"engine,omitempty"`
	EngineVersion           string                 `protobuf:"bytes,4,opt,name=engine_version,json=engineVersion,proto3" json:"engine_version,omitempty"`
	SteamAppIdLinux         *uint32                `protobuf:"varint,5,opt,name=steam_app_id_linux,json=steamAppIdLinux,proto3,oneof" json:"steam_app_id_linux,omitempty"`
	SteamAppIdWindows       *uint32                `protobuf:"varint,6,opt,name=steam_app_id_windows,json=steamAppIdWindows,proto3,oneof" json:"steam_app_id_windows,omitempty"`
	SteamAppSetConfig       *string                `protobuf:"bytes,7,opt,name=steam_app_set_config,json=steamAppSetConfig,proto3,oneof" json:"steam_app_set_config,omitempty"`
	RemoteRepositoryLinux   *string                `protobuf:"bytes,8,opt,name=remote_repository_linux,json=remoteRepositoryLinux,proto3,oneof" json:"remote_repository_linux,omitempty"`
	RemoteRepositoryWindows *string                `protobuf:"bytes,9,opt,name=remote_repository_windows,json=remoteRepositoryWindows,proto3,oneof" json:"remote_repository_windows,omitempty"`
	Enabled                 bool                   `protobuf:"varint,10,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *Game) Reset() {
	*x = Game{}
	mi := &file_game_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Game) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Game) ProtoMessage() {}

func (x *Game) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Game.ProtoReflect.Descriptor instead.
func (*Game) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{0}
}

func (x *Game) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Game) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Game) GetEngine() string {
	if x != nil {
		return x.Engine
	}
	return ""
}

func (x *Game) GetEngineVersion() string {
	if x != nil {
		return x.EngineVersion
	}
	return ""
}

func (x *Game) GetSteamAppIdLinux() uint32 {
	if x != nil && x.SteamAppIdLinux != nil {
		return *x.SteamAppIdLinux
	}
	return 0
}

func (x *Game) GetSteamAppIdWindows() uint32 {
	if x != nil && x.SteamAppIdWindows != nil {
		return *x.SteamAppIdWindows
	}
	return 0
}

func (x *Game) GetSteamAppSetConfig() string {
	if x != nil && x.SteamAppSetConfig != nil {
		return *x.SteamAppSetConfig
	}
	return ""
}

func (x *Game) GetRemoteRepositoryLinux() string {
	if x != nil && x.RemoteRepositoryLinux != nil {
		return *x.RemoteRepositoryLinux
	}
	return ""
}

func (x *Game) GetRemoteRepositoryWindows() string {
	if x != nil && x.RemoteRepositoryWindows != nil {
		return *x.RemoteRepositoryWindows
	}
	return ""
}

func (x *Game) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

var File_game_proto protoreflect.FileDescriptor

const file_game_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"game.proto\x12\x06gameap\"\xa6\x04\n" +
	"\x04Game\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06engine\x18\x03 \x01(\tR\x06engine\x12%\n" +
	"\x0eengine_version\x18\x04 \x01(\tR\rengineVersion\x120\n" +
	"\x12steam_app_id_linux\x18\x05 \x01(\rH\x00R\x0fsteamAppIdLinux\x88\x01\x01\x124\n" +
	"\x14steam_app_id_windows\x18\x06 \x01(\rH\x01R\x11steamAppIdWindows\x88\x01\x01\x124\n" +
	"\x14steam_app_set_config\x18\a \x01(\tH\x02R\x11steamAppSetConfig\x88\x01\x01\x12;\n" +
	"\x17remote_repository_linux\x18\b \x01(\tH\x03R\x15remoteRepositoryLinux\x88\x01\x01\x12?\n" +
	"\x19remote_repository_windows\x18\t \x01(\tH\x04R\x17remoteRepositoryWindows\x88\x01\x01\x12\x18\n" +
	"\aenabled\x18\n" +
	" \x01(\bR\aenabledB\x15\n" +
	"\x13_steam_app_id_linuxB\x17\n" +
	"\x15_steam_app_id_windowsB\x17\n" +
	"\x15_steam_app_set_configB\x1a\n" +
	"\x18_remote_repository_linuxB\x1c\n" +
	"\x1a_remote_repository_windowsB$Z\"github.com/gameap/gameap/pkg/protob\x06proto3"

var (
	file_game_proto_rawDescOnce sync.Once
	file_game_proto_rawDescData []byte
)

func file_game_proto_rawDescGZIP() []byte {
	file_game_proto_rawDescOnce.Do(func() {
		file_game_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_game_proto_rawDesc), len(file_game_proto_rawDesc)))
	})
	return file_game_proto_rawDescData
}

var file_game_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_game_proto_goTypes = []any{
	(*Game)(nil), // 0: gameap.Game
}
var file_game_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_game_proto_init() }
func file_game_proto_init() {
	if File_game_proto != nil {
		return
	}
	file_game_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_game_proto_rawDesc), len(file_game_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_game_proto_goTypes,
		DependencyIndexes: file_game_proto_depIdxs,
		MessageInfos:      file_game_proto_msgTypes,
	}.Build()
	File_game_proto = out.File
	file_game_proto_goTypes = nil
	file_game_proto_depIdxs = nil
}
