// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: gamemod.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GameMod struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	GameCode        string                 `protobuf:"bytes,2,opt,name=game_code,json=gameCode,proto3" json:"game_code,omitempty"`
	Name            string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	StartCmdLinux   *string                `protobuf:"bytes,4,opt,name=start_cmd_linux,json=startCmdLinux,proto3,oneof" json:"start_cmd_linux,omitempty"`
	StartCmdWindows *string                `protobuf:"bytes,5,opt,name=start_cmd_windows,json=startCmdWindows,proto3,oneof" json:"start_cmd_windows,omitempty"`
	KickCmd         *string                `protobuf:"bytes,6,opt,name=kick_cmd,json=kickCmd,proto3,oneof" json:"kick_cmd,omitempty"`
	BanCmd          *string                `protobuf:"bytes,7,opt,name=ban_cmd,json=banCmd,proto3,oneof" json:"ban_cmd,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GameMod) Reset() {
	*x = GameMod{}
	mi := &file_gamemod_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameMod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameMod) ProtoMessage() {}

func (x *GameMod) ProtoReflect() protoreflect.Message {
	mi := &file_gamemod_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameMod.ProtoReflect.Descriptor instead.
func (*GameMod) Descriptor() ([]byte, []int) {
	return file_gamemod_proto_rawDescGZIP(), []int{0}
}

func (x *GameMod) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GameMod) GetGameCode() string {
	if x != nil {
		return x.GameCode
	}
	return ""
}

func (x *GameMod) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GameMod) GetStartCmdLinux() string {
	if x != nil && x.StartCmdLinux != nil {
		return *x.StartCmdLinux
	}
	return ""
}

func (x *GameMod) GetStartCmdWindows() string {
	if x != nil && x.StartCmdWindows != nil {
		return *x.StartCmdWindows
	}
	return ""
}

func (x *GameMod) GetKickCmd() string {
	if x != nil && x.KickCmd != nil {
		return *x.KickCmd
	}
	return ""
}

func (x *GameMod) GetBanCmd() string {
	if x != nil && x.BanCmd != nil {
		return *x.BanCmd
	}
	return ""
}

var File_gamemod_proto protoreflect.FileDescriptor

const file_gamemod_proto_rawDesc = "" +
	"\n" +
	"\rgamemod.proto\x12\x06gameap\"\xa9\x02\n" +
	"\aGameMod\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1b\n" +
	"\tgame_code\x18\x02 \x01(\tR\bgameCode\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12+\n" +
	"\x0fstart_cmd_linux\x18\x04 \x01(\tH\x00R\rstartCmdLinux\x88\x01\x01\x12/\n" +
	"\x11start_cmd_windows\x18\x05 \x01(\tH\x01R\x0fstartCmdWindows\x88\x01\x01\x12\x1e\n" +
	"\bkick_cmd\x18\x06 \x01(\tH\x02R\akickCmd\x88\x01\x01\x12\x1c\n" +
	"\aban_cmd\x18\a \x01(\tH\x03R\x06banCmd\x88\x01\x01B\x12\n" +
	"\x10_start_cmd_linuxB\x14\n" +
	"\x12_start_cmd_windowsB\v\n" +
	"\t_kick_cmdB\n" +
	"\n" +
	"\b_ban_cmdB$Z\"github.com/gameap/gameap/pkg/protob\x06proto3"

var (
	file_gamemod_proto_rawDescOnce sync.Once
	file_gamemod_proto_rawDescData []byte
)

func file_gamemod_proto_rawDescGZIP() []byte {
	file_gamemod_proto_rawDescOnce.Do(func() {
		file_gamemod_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gamemod_proto_rawDesc), len(file_gamemod_proto_rawDesc)))
	})
	return file_gamemod_proto_rawDescData
}

var file_gamemod_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_gamemod_proto_goTypes = []any{
	(*GameMod)(nil), // 0: gameap.GameMod
}
var file_gamemod_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_gamemod_proto_init() }
func file_gamemod_proto_init() {
	if File_gamemod_proto != nil {
		return
	}
	file_gamemod_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gamemod_proto_rawDesc), len(file_gamemod_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gamemod_proto_goTypes,
		DependencyIndexes: file_gamemod_proto_depIdxs,
		MessageInfos:      file_gamemod_proto_msgTypes,
	}.Build()
	File_gamemod_proto = out.File
	file_gamemod_proto_goTypes = nil
	file_gamemod_proto_depIdxs = nil
}
