// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: pkg/proto/gateway.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DaemonMessage struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RequestId string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*DaemonMessage_Register
	//	*DaemonMessage_Heartbeat
	//	*DaemonMessage_TaskStatus
	//	*DaemonMessage_TaskOutput
	//	*DaemonMessage_CommandOutput
	//	*DaemonMessage_CommandResult
	//	*DaemonMessage_AttachStarted
	//	*DaemonMessage_AttachOutput
	//	*DaemonMessage_AttachClosed
	//	*DaemonMessage_ServerStatuses
	//	*DaemonMessage_FileReadResponse
	//	*DaemonMessage_FileWriteResponse
	//	*DaemonMessage_FileListResponse
	//	*DaemonMessage_FileOperationResponse
	//	*DaemonMessage_StatusResponse
	Payload       isDaemonMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DaemonMessage) Reset() {
	*x = DaemonMessage{}
	mi := &file_pkg_proto_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DaemonMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DaemonMessage) ProtoMessage() {}

func (x *DaemonMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DaemonMessage.ProtoReflect.Descriptor instead.
func (*DaemonMessage) Descriptor() ([]byte, []int) {
	return file_pkg_proto_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *DaemonMessage) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *DaemonMessage) GetPayload() isDaemonMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *DaemonMessage) GetRegister() *RegisterRequest {
	if x != nil {
		if x, ok := x.Payload.(*DaemonMessage_Register); ok {
			return x.Register
		}
	}
	return nil
}

func (x *DaemonMessage) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*DaemonMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *DaemonMessage) GetTaskStatus() *TaskStatusUpdate {
	if x != nil {
		if x, ok := x.Payload.(*DaemonMessage_TaskStatus); ok {
			return x.TaskStatus
		}
	}
	return nil
}

func (x *DaemonMessage) GetTaskOutput() *TaskOutput {
	if x != nil {
		if x, ok := x.Payload.(*DaemonMessage_TaskOutput); ok {
			return x.TaskOutput
		}
	}
	return nil
}

func (x *DaemonMessage) GetCommandOutput() *CommandOutput {
	if x != nil {
		if x, ok := x.Payload.(*DaemonMessage_CommandOutput); ok {
			return x.CommandOutput
		}
	}
	return nil
}

func (x *DaemonMessage) GetCommandResult() *CommandResult {
	if x != nil {
		if x, ok := x.Payload.(*DaemonMessage_CommandResult); ok {
			return x.CommandResult
		}
	}
	return nil
}

func (x *DaemonMessage) GetAttachStarted() *AttachStarted {
	if x != nil {
		if x, ok := x.Payload.(*DaemonMessage_AttachStarted); ok {
			return x.AttachStarted
		}
	}
	return nil
}

func (x *DaemonMessage) GetAttachOutput() *AttachOutput {
	if x != nil {
		if x, ok := x.Payload.(*DaemonMessage_AttachOutput); ok {
			return x.AttachOutput
		}
	}
	return nil
}

func (x *DaemonMessage) GetAttachClosed() *AttachClosed {
	if x != nil {
		if x, ok := x.Payload.(*DaemonMessage_AttachClosed); ok {
			return x.AttachClosed
		}
	}
	return nil
}

func (x *DaemonMessage) GetServerStatuses() *ServerStatusBatch {
	if x != nil {
		if x, ok := x.Payload.(*DaemonMessage_ServerStatuses); ok {
			return x.ServerStatuses
		}
	}
	return nil
}

func (x *DaemonMessage) GetFileReadResponse() *FileReadResponse {
	if x != nil {
		if x, ok := x.Payload.(*DaemonMessage_FileReadResponse); ok {
			return x.FileReadResponse
		}
	}
	return nil
}

func (x *DaemonMessage) GetFileWriteResponse() *FileWriteResponse {
	if x != nil {
		if x, ok := x.Payload.(*DaemonMessage_FileWriteResponse); ok {
			return x.FileWriteResponse
		}
	}
	return nil
}

func (x *DaemonMessage) GetFileListResponse() *FileListResponse {
	if x != nil {
		if x, ok := x.Payload.(*DaemonMessage_FileListResponse); ok {
			return x.FileListResponse
		}
	}
	return nil
}

func (x *DaemonMessage) GetFileOperationResponse() *FileOperationResponse {
	if x != nil {
		if x, ok := x.Payload.(*DaemonMessage_FileOperationResponse); ok {
			return x.FileOperationResponse
		}
	}
	return nil
}

func (x *DaemonMessage) GetStatusResponse() *StatusResponse {
	if x != nil {
		if x, ok := x.Payload.(*DaemonMessage_StatusResponse); ok {
			return x.StatusResponse
		}
	}
	return nil
}

type isDaemonMessage_Payload interface {
	isDaemonMessage_Payload()
}

type DaemonMessage_Register struct {
	Register *RegisterRequest `protobuf:"bytes,10,opt,name=register,proto3,oneof"`
}

type DaemonMessage_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,11,opt,name=heartbeat,proto3,oneof"`
}

type DaemonMessage_TaskStatus struct {
	TaskStatus *TaskStatusUpdate `protobuf:"bytes,20,opt,name=task_status,json=taskStatus,proto3,oneof"`
}

type DaemonMessage_TaskOutput struct {
	TaskOutput *TaskOutput `protobuf:"bytes,21,opt,name=task_output,json=taskOutput,proto3,oneof"`
}

type DaemonMessage_CommandOutput struct {
	CommandOutput *CommandOutput `protobuf:"bytes,30,opt,name=command_output,json=commandOutput,proto3,oneof"`
}

type DaemonMessage_CommandResult struct {
	CommandResult *CommandResult `protobuf:"bytes,31,opt,name=command_result,json=commandResult,proto3,oneof"`
}

type DaemonMessage_AttachStarted struct {
	AttachStarted *AttachStarted `protobuf:"bytes,32,opt,name=attach_started,json=attachStarted,proto3,oneof"`
}

type DaemonMessage_AttachOutput struct {
	AttachOutput *AttachOutput `protobuf:"bytes,33,opt,name=attach_output,json=attachOutput,proto3,oneof"`
}

type DaemonMessage_AttachClosed struct {
	AttachClosed *AttachClosed `protobuf:"bytes,34,opt,name=attach_closed,json=attachClosed,proto3,oneof"`
}

type DaemonMessage_ServerStatuses struct {
	ServerStatuses *ServerStatusBatch `protobuf:"bytes,50,opt,name=server_statuses,json=serverStatuses,proto3,oneof"`
}

type DaemonMessage_FileReadResponse struct {
	FileReadResponse *FileReadResponse `protobuf:"bytes,60,opt,name=file_read_response,json=fileReadResponse,proto3,oneof"`
}

type DaemonMessage_FileWriteResponse struct {
	FileWriteResponse *FileWriteResponse `protobuf:"bytes,61,opt,name=file_write_response,json=fileWriteResponse,proto3,oneof"`
}

type DaemonMessage_FileListResponse struct {
	FileListResponse *FileListResponse `protobuf:"bytes,62,opt,name=file_list_response,json=fileListResponse,proto3,oneof"`
}

type DaemonMessage_FileOperationResponse struct {
	FileOperationResponse *FileOperationResponse `protobuf:"bytes,63,opt,name=file_operation_response,json=fileOperationResponse,proto3,oneof"`
}

type DaemonMessage_StatusResponse struct {
	StatusResponse *StatusResponse `protobuf:"bytes,70,opt,name=status_response,json=statusResponse,proto3,oneof"`
}

func (*DaemonMessage_Register) isDaemonMessage_Payload() {}

func (*DaemonMessage_Heartbeat) isDaemonMessage_Payload() {}

func (*DaemonMessage_TaskStatus) isDaemonMessage_Payload() {}

func (*DaemonMessage_TaskOutput) isDaemonMessage_Payload() {}

func (*DaemonMessage_CommandOutput) isDaemonMessage_Payload() {}

func (*DaemonMessage_CommandResult) isDaemonMessage_Payload() {}

func (*DaemonMessage_AttachStarted) isDaemonMessage_Payload() {}

func (*DaemonMessage_AttachOutput) isDaemonMessage_Payload() {}

func (*DaemonMessage_AttachClosed) isDaemonMessage_Payload() {}

func (*DaemonMessage_ServerStatuses) isDaemonMessage_Payload() {}

func (*DaemonMessage_FileReadResponse) isDaemonMessage_Payload() {}

func (*DaemonMessage_FileWriteResponse) isDaemonMessage_Payload() {}

func (*DaemonMessage_FileListResponse) isDaemonMessage_Payload() {}

func (*DaemonMessage_FileOperationResponse) isDaemonMessage_Payload() {}

func (*DaemonMessage_StatusResponse) isDaemonMessage_Payload() {}

type GatewayMessage struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RequestId string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*GatewayMessage_RegisterAck
	//	*GatewayMessage_Shutdown
	//	*GatewayMessage_Task
	//	*GatewayMessage_TaskCancel
	//	*GatewayMessage_Command
	//	*GatewayMessage_AttachRequest
	//	*GatewayMessage_AttachInput
	//	*GatewayMessage_AttachDetach
	//	*GatewayMessage_ServerConfig
	//	*GatewayMessage_ServerConfigBatch
	//	*GatewayMessage_FileRead
	//	*GatewayMessage_FileWrite
	//	*GatewayMessage_FileList
	//	*GatewayMessage_FileUploadTask
	//	*GatewayMessage_FileOperation
	//	*GatewayMessage_FileDownloadTask
	//	*GatewayMessage_StatusRequest
	Payload       isGatewayMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GatewayMessage) Reset() {
	*x = GatewayMessage{}
	mi := &file_pkg_proto_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayMessage) ProtoMessage() {}

func (x *GatewayMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayMessage.ProtoReflect.Descriptor instead.
func (*GatewayMessage) Descriptor() ([]byte, []int) {
	return file_pkg_proto_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *GatewayMessage) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *GatewayMessage) GetPayload() isGatewayMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *GatewayMessage) GetRegisterAck() *RegisterAck {
	if x != nil {
		if x, ok := x.Payload.(*GatewayMessage_RegisterAck); ok {
			return x.RegisterAck
		}
	}
	return nil
}

func (x *GatewayMessage) GetShutdown() *ShutdownNotification {
	if x != nil {
		if x, ok := x.Payload.(*GatewayMessage_Shutdown); ok {
			return x.Shutdown
		}
	}
	return nil
}

func (x *GatewayMessage) GetTask() *DaemonTask {
	if x != nil {
		if x, ok := x.Payload.(*GatewayMessage_Task); ok {
			return x.Task
		}
	}
	return nil
}

func (x *GatewayMessage) GetTaskCancel() *TaskCancel {
	if x != nil {
		if x, ok := x.Payload.(*GatewayMessage_TaskCancel); ok {
			return x.TaskCancel
		}
	}
	return nil
}

func (x *GatewayMessage) GetCommand() *CommandRequest {
	if x != nil {
		if x, ok := x.Payload.(*GatewayMessage_Command); ok {
			return x.Command
		}
	}
	return nil
}

func (x *GatewayMessage) GetAttachRequest() *AttachRequest {
	if x != nil {
		if x, ok := x.Payload.(*GatewayMessage_AttachRequest); ok {
			return x.AttachRequest
		}
	}
	return nil
}

func (x *GatewayMessage) GetAttachInput() *AttachInput {
	if x != nil {
		if x, ok := x.Payload.(*GatewayMessage_AttachInput); ok {
			return x.AttachInput
		}
	}
	return nil
}

func (x *GatewayMessage) GetAttachDetach() *AttachDetach {
	if x != nil {
		if x, ok := x.Payload.(*GatewayMessage_AttachDetach); ok {
			return x.AttachDetach
		}
	}
	return nil
}

func (x *GatewayMessage) GetServerConfig() *Server {
	if x != nil {
		if x, ok := x.Payload.(*GatewayMessage_ServerConfig); ok {
			return x.ServerConfig
		}
	}
	return nil
}

func (x *GatewayMessage) GetServerConfigBatch() *ServerConfigBatch {
	if x != nil {
		if x, ok := x.Payload.(*GatewayMessage_ServerConfigBatch); ok {
			return x.ServerConfigBatch
		}
	}
	return nil
}

func (x *GatewayMessage) GetFileRead() *FileReadRequest {
	if x != nil {
		if x, ok := x.Payload.(*GatewayMessage_FileRead); ok {
			return x.FileRead
		}
	}
	return nil
}

func (x *GatewayMessage) GetFileWrite() *FileWriteRequest {
	if x != nil {
		if x, ok := x.Payload.(*GatewayMessage_FileWrite); ok {
			return x.FileWrite
		}
	}
	return nil
}

func (x *GatewayMessage) GetFileList() *FileListRequest {
	if x != nil {
		if x, ok := x.Payload.(*GatewayMessage_FileList); ok {
			return x.FileList
		}
	}
	return nil
}

func (x *GatewayMessage) GetFileUploadTask() *FileUploadTask {
	if x != nil {
		if x, ok := x.Payload.(*GatewayMessage_FileUploadTask); ok {
			return x.FileUploadTask
		}
	}
	return nil
}

func (x *GatewayMessage) GetFileOperation() *FileOperationRequest {
	if x != nil {
		if x, ok := x.Payload.(*GatewayMessage_FileOperation); ok {
			return x.FileOperation
		}
	}
	return nil
}

func (x *GatewayMessage) GetFileDownloadTask() *FileDownloadTask {
	if x != nil {
		if x, ok := x.Payload.(*GatewayMessage_FileDownloadTask); ok {
			return x.FileDownloadTask
		}
	}
	return nil
}

func (x *GatewayMessage) GetStatusRequest() *StatusRequest {
	if x != nil {
		if x, ok := x.Payload.(*GatewayMessage_StatusRequest); ok {
			return x.StatusRequest
		}
	}
	return nil
}

type isGatewayMessage_Payload interface {
	isGatewayMessage_Payload()
}

type GatewayMessage_RegisterAck struct {
	RegisterAck *RegisterAck `protobuf:"bytes,10,opt,name=register_ack,json=registerAck,proto3,oneof"`
}

type GatewayMessage_Shutdown struct {
	Shutdown *ShutdownNotification `protobuf:"bytes,11,opt,name=shutdown,proto3,oneof"`
}

type GatewayMessage_Task struct {
	Task *DaemonTask `protobuf:"bytes,20,opt,name=task,proto3,oneof"`
}

type GatewayMessage_TaskCancel struct {
	TaskCancel *TaskCancel `protobuf:"bytes,21,opt,name=task_cancel,json=taskCancel,proto3,oneof"`
}

type GatewayMessage_Command struct {
	Command *CommandRequest `protobuf:"bytes,30,opt,name=command,proto3,oneof"`
}

type GatewayMessage_AttachRequest struct {
	AttachRequest *AttachRequest `protobuf:"bytes,34,opt,name=attach_request,json=attachRequest,proto3,oneof"`
}

type GatewayMessage_AttachInput struct {
	AttachInput *AttachInput `protobuf:"bytes,35,opt,name=attach_input,json=attachInput,proto3,oneof"`
}

type GatewayMessage_AttachDetach struct {
	AttachDetach *AttachDetach `protobuf:"bytes,36,opt,name=attach_detach,json=attachDetach,proto3,oneof"`
}

type GatewayMessage_ServerConfig struct {
	ServerConfig *Server `protobuf:"bytes,50,opt,name=server_config,json=serverConfig,proto3,oneof"`
}

type GatewayMessage_ServerConfigBatch struct {
	ServerConfigBatch *ServerConfigBatch `protobuf:"bytes,51,opt,name=server_config_batch,json=serverConfigBatch,proto3,oneof"`
}

type GatewayMessage_FileRead struct {
	FileRead *FileReadRequest `protobuf:"bytes,60,opt,name=file_read,json=fileRead,proto3,oneof"`
}

type GatewayMessage_FileWrite struct {
	FileWrite *FileWriteRequest `protobuf:"bytes,61,opt,name=file_write,json=fileWrite,proto3,oneof"`
}

type GatewayMessage_FileList struct {
	FileList *FileListRequest `protobuf:"bytes,62,opt,name=file_list,json=fileList,proto3,oneof"`
}

type GatewayMessage_FileUploadTask struct {
	FileUploadTask *FileUploadTask `protobuf:"bytes,63,opt,name=file_upload_task,json=fileUploadTask,proto3,oneof"`
}

type GatewayMessage_FileOperation struct {
	FileOperation *FileOperationRequest `protobuf:"bytes,64,opt,name=file_operation,json=fileOperation,proto3,oneof"`
}

type GatewayMessage_FileDownloadTask struct {
	FileDownloadTask *FileDownloadTask `protobuf:"bytes,65,opt,name=file_download_task,json=fileDownloadTask,proto3,oneof"`
}

type GatewayMessage_StatusRequest struct {
	StatusRequest *StatusRequest `protobuf:"bytes,70,opt,name=status_request,json=statusRequest,proto3,oneof"`
}

func (*GatewayMessage_RegisterAck) isGatewayMessage_Payload() {}

func (*GatewayMessage_Shutdown) isGatewayMessage_Payload() {}

func (*GatewayMessage_Task) isGatewayMessage_Payload() {}

func (*GatewayMessage_TaskCancel) isGatewayMessage_Payload() {}

func (*GatewayMessage_Command) isGatewayMessage_Payload() {}

func (*GatewayMessage_AttachRequest) isGatewayMessage_Payload() {}

func (*GatewayMessage_AttachInput) isGatewayMessage_Payload() {}

func (*GatewayMessage_AttachDetach) isGatewayMessage_Payload() {}

func (*GatewayMessage_ServerConfig) isGatewayMessage_Payload() {}

func (*GatewayMessage_ServerConfigBatch) isGatewayMessage_Payload() {}

func (*GatewayMessage_FileRead) isGatewayMessage_Payload() {}

func (*GatewayMessage_FileWrite) isGatewayMessage_Payload() {}

func (*GatewayMessage_FileList) isGatewayMessage_Payload() {}

func (*GatewayMessage_FileUploadTask) isGatewayMessage_Payload() {}

func (*GatewayMessage_FileOperation) isGatewayMessage_Payload() {}

func (*GatewayMessage_FileDownloadTask) isGatewayMessage_Payload() {}

func (*GatewayMessage_StatusRequest) isGatewayMessage_Payload() {}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        uint64                 `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	ApiKey        string                 `protobuf:"bytes,2,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Capabilities  []string               `protobuf:"bytes,4,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	InFlightTasks []*InFlightTask        `protobuf:"bytes,5,rep,name=in_flight_tasks,json=inFlightTasks,proto3" json:"in_flight_tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_pkg_proto_gateway_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_gateway_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_gateway_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterRequest) GetNodeId() uint64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *RegisterRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *RegisterRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *RegisterRequest) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *RegisterRequest) GetInFlightTasks() []*InFlightTask {
	if x != nil {
		return x.InFlightTasks
	}
	return nil
}

type InFlightTask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        uint64                 `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Status        DaemonTaskStatus       `protobuf:"varint,2,opt,name=status,proto3,enum=gameap.DaemonTaskStatus" json:"status,omitempty"`
	PartialOutput string                 `protobuf:"bytes,3,opt,name=partial_output,json=partialOutput,proto3" json:"partial_output,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InFlightTask) Reset() {
	*x = InFlightTask{}
	mi := &file_pkg_proto_gateway_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InFlightTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InFlightTask) ProtoMessage() {}

func (x *InFlightTask) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_gateway_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InFlightTask.ProtoReflect.Descriptor instead.
func (*InFlightTask) Descriptor() ([]byte, []int) {
	return file_pkg_proto_gateway_proto_rawDescGZIP(), []int{3}
}

func (x *InFlightTask) GetTaskId() uint64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *InFlightTask) GetStatus() DaemonTaskStatus {
	if x != nil {
		return x.Status
	}
	return DaemonTaskStatus_DAEMON_TASK_STATUS_UNSPECIFIED
}

func (x *InFlightTask) GetPartialOutput() string {
	if x != nil {
		return x.PartialOutput
	}
	return ""
}

func (x *InFlightTask) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

type RegisterAck struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Success           bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage      string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Servers           []*Server              `protobuf:"bytes,3,rep,name=servers,proto3" json:"servers,omitempty"`
	PendingTasks      []*DaemonTask          `protobuf:"bytes,4,rep,name=pending_tasks,json=pendingTasks,proto3" json:"pending_tasks,omitempty"`
	Games             []*Game                `protobuf:"bytes,5,rep,name=games,proto3" json:"games,omitempty"`
	GameMods          []*GameMod             `protobuf:"bytes,6,rep,name=game_mods,json=gameMods,proto3" json:"game_mods,omitempty"`
	HeartbeatInterval *durationpb.Duration   `protobuf:"bytes,7,opt,name=heartbeat_interval,json=heartbeatInterval,proto3" json:"heartbeat_interval,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RegisterAck) Reset() {
	*x = RegisterAck{}
	mi := &file_pkg_proto_gateway_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAck) ProtoMessage() {}

func (x *RegisterAck) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_gateway_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAck.ProtoReflect.Descriptor instead.
func (*RegisterAck) Descriptor() ([]byte, []int) {
	return file_pkg_proto_gateway_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterAck) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterAck) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *RegisterAck) GetServers() []*Server {
	if x != nil {
		return x.Servers
	}
	return nil
}

func (x *RegisterAck) GetPendingTasks() []*DaemonTask {
	if x != nil {
		return x.PendingTasks
	}
	return nil
}

func (x *RegisterAck) GetGames() []*Game {
	if x != nil {
		return x.Games
	}
	return nil
}

func (x *RegisterAck) GetGameMods() []*GameMod {
	if x != nil {
		return x.GameMods
	}
	return nil
}

func (x *RegisterAck) GetHeartbeatInterval() *durationpb.Duration {
	if x != nil {
		return x.HeartbeatInterval
	}
	return nil
}

type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	SystemStats   *SystemStats           `protobuf:"bytes,2,opt,name=system_stats,json=systemStats,proto3" json:"system_stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_pkg_proto_gateway_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_gateway_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_pkg_proto_gateway_proto_rawDescGZIP(), []int{5}
}

func (x *Heartbeat) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Heartbeat) GetSystemStats() *SystemStats {
	if x != nil {
		return x.SystemStats
	}
	return nil
}

type SystemStats struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	LoadAverage_1M   float64                `protobuf:"fixed64,1,opt,name=load_average_1m,json=loadAverage1m,proto3" json:"load_average_1m,omitempty"`
	LoadAverage_5M   float64                `protobuf:"fixed64,2,opt,name=load_average_5m,json=loadAverage5m,proto3" json:"load_average_5m,omitempty"`
	LoadAverage_15M  float64                `protobuf:"fixed64,3,opt,name=load_average_15m,json=loadAverage15m,proto3" json:"load_average_15m,omitempty"`
	CpuUsagePercent  float64                `protobuf:"fixed64,4,opt,name=cpu_usage_percent,json=cpuUsagePercent,proto3" json:"cpu_usage_percent,omitempty"`
	MemoryUsedBytes  uint64                 `protobuf:"varint,5,opt,name=memory_used_bytes,json=memoryUsedBytes,proto3" json:"memory_used_bytes,omitempty"`
	MemoryTotalBytes uint64                 `protobuf:"varint,6,opt,name=memory_total_bytes,json=memoryTotalBytes,proto3" json:"memory_total_bytes,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SystemStats) Reset() {
	*x = SystemStats{}
	mi := &file_pkg_proto_gateway_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemStats) ProtoMessage() {}

func (x *SystemStats) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_gateway_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemStats.ProtoReflect.Descriptor instead.
func (*SystemStats) Descriptor() ([]byte, []int) {
	return file_pkg_proto_gateway_proto_rawDescGZIP(), []int{6}
}

func (x *SystemStats) GetLoadAverage_1M() float64 {
	if x != nil {
		return x.LoadAverage_1M
	}
	return 0
}

func (x *SystemStats) GetLoadAverage_5M() float64 {
	if x != nil {
		return x.LoadAverage_5M
	}
	return 0
}

func (x *SystemStats) GetLoadAverage_15M() float64 {
	if x != nil {
		return x.LoadAverage_15M
	}
	return 0
}

func (x *SystemStats) GetCpuUsagePercent() float64 {
	if x != nil {
		return x.CpuUsagePercent
	}
	return 0
}

func (x *SystemStats) GetMemoryUsedBytes() uint64 {
	if x != nil {
		return x.MemoryUsedBytes
	}
	return 0
}

func (x *SystemStats) GetMemoryTotalBytes() uint64 {
	if x != nil {
		return x.MemoryTotalBytes
	}
	return 0
}

type TaskStatusUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        uint64                 `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Status        DaemonTaskStatus       `protobuf:"varint,2,opt,name=status,proto3,enum=gameap.DaemonTaskStatus" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskStatusUpdate) Reset() {
	*x = TaskStatusUpdate{}
	mi := &file_pkg_proto_gateway_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskStatusUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskStatusUpdate) ProtoMessage() {}

func (x *TaskStatusUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_gateway_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskStatusUpdate.ProtoReflect.Descriptor instead.
func (*TaskStatusUpdate) Descriptor() ([]byte, []int) {
	return file_pkg_proto_gateway_proto_rawDescGZIP(), []int{7}
}

func (x *TaskStatusUpdate) GetTaskId() uint64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *TaskStatusUpdate) GetStatus() DaemonTaskStatus {
	if x != nil {
		return x.Status
	}
	return DaemonTaskStatus_DAEMON_TASK_STATUS_UNSPECIFIED
}

func (x *TaskStatusUpdate) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type TaskOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        uint64                 `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	OutputChunk   []byte                 `protobuf:"bytes,2,opt,name=output_chunk,json=outputChunk,proto3" json:"output_chunk,omitempty"`
	IsFinal       bool                   `protobuf:"varint,3,opt,name=is_final,json=isFinal,proto3" json:"is_final,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskOutput) Reset() {
	*x = TaskOutput{}
	mi := &file_pkg_proto_gateway_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskOutput) ProtoMessage() {}

func (x *TaskOutput) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_gateway_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskOutput.ProtoReflect.Descriptor instead.
func (*TaskOutput) Descriptor() ([]byte, []int) {
	return file_pkg_proto_gateway_proto_rawDescGZIP(), []int{8}
}

func (x *TaskOutput) GetTaskId() uint64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *TaskOutput) GetOutputChunk() []byte {
	if x != nil {
		return x.OutputChunk
	}
	return nil
}

func (x *TaskOutput) GetIsFinal() bool {
	if x != nil {
		return x.IsFinal
	}
	return false
}

type TaskCancel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        uint64                 `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskCancel) Reset() {
	*x = TaskCancel{}
	mi := &file_pkg_proto_gateway_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskCancel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskCancel) ProtoMessage() {}

func (x *TaskCancel) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_gateway_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskCancel.ProtoReflect.Descriptor instead.
func (*TaskCancel) Descriptor() ([]byte, []int) {
	return file_pkg_proto_gateway_proto_rawDescGZIP(), []int{9}
}

func (x *TaskCancel) GetTaskId() uint64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *TaskCancel) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type CommandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	ServerId      uint64                 `protobuf:"varint,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Command       string                 `protobuf:"bytes,3,opt,name=command,proto3" json:"command,omitempty"`
	Timeout       *durationpb.Duration   `protobuf:"bytes,4,opt,name=timeout,proto3" json:"timeout,omitempty"`
	StreamOutput  bool                   `protobuf:"varint,5,opt,name=stream_output,json=streamOutput,proto3" json:"stream_output,omitempty"`
	WorkDir       string                 `protobuf:"bytes,6,opt,name=work_dir,json=workDir,proto3" json:"work_dir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandRequest) Reset() {
	*x = CommandRequest{}
	mi := &file_pkg_proto_gateway_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandRequest) ProtoMessage() {}

func (x *CommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_gateway_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandRequest.ProtoReflect.Descriptor instead.
func (*CommandRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_gateway_proto_rawDescGZIP(), []int{10}
}

func (x *CommandRequest) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *CommandRequest) GetServerId() uint64 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

func (x *CommandRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *CommandRequest) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

func (x *CommandRequest) GetStreamOutput() bool {
	if x != nil {
		return x.StreamOutput
	}
	return false
}

func (x *CommandRequest) GetWorkDir() string {
	if x != nil {
		return x.WorkDir
	}
	return ""
}

type CommandOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	OutputChunk   []byte                 `protobuf:"bytes,2,opt,name=output_chunk,json=outputChunk,proto3" json:"output_chunk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandOutput) Reset() {
	*x = CommandOutput{}
	mi := &file_pkg_proto_gateway_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandOutput) ProtoMessage() {}

func (x *CommandOutput) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_gateway_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandOutput.ProtoReflect.Descriptor instead.
func (*CommandOutput) Descriptor() ([]byte, []int) {
	return file_pkg_proto_gateway_proto_rawDescGZIP(), []int{11}
}

func (x *CommandOutput) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *CommandOutput) GetOutputChunk() []byte {
	if x != nil {
		return x.OutputChunk
	}
	return nil
}

type CommandResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	ExitCode      int32                  `protobuf:"varint,2,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Output        []byte                 `protobuf:"bytes,3,opt,name=output,proto3" json:"output,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	RequestId     string                 `protobuf:"bytes,5,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResult) Reset() {
	*x = CommandResult{}
	mi := &file_pkg_proto_gateway_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResult) ProtoMessage() {}

func (x *CommandResult) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_gateway_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResult.ProtoReflect.Descriptor instead.
func (*CommandResult) Descriptor() ([]byte, []int) {
	return file_pkg_proto_gateway_proto_rawDescGZIP(), []int{12}
}

func (x *CommandResult) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *CommandResult) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *CommandResult) GetOutput() []byte {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *CommandResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *CommandResult) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type ServerStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      uint64                 `protobuf:"varint,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	IsRunning     bool                   `protobuf:"varint,2,opt,name=is_running,json=isRunning,proto3" json:"is_running,omitempty"`
	LastCheck     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=last_check,json=lastCheck,proto3" json:"last_check,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerStatus) Reset() {
	*x = ServerStatus{}
	mi := &file_pkg_proto_gateway_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerStatus) ProtoMessage() {}

func (x *ServerStatus) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_gateway_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerStatus.ProtoReflect.Descriptor instead.
func (*ServerStatus) Descriptor() ([]byte, []int) {
	return file_pkg_proto_gateway_proto_rawDescGZIP(), []int{13}
}

func (x *ServerStatus) GetServerId() uint64 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

func (x *ServerStatus) GetIsRunning() bool {
	if x != nil {
		return x.IsRunning
	}
	return false
}

func (x *ServerStatus) GetLastCheck() *timestamppb.Timestamp {
	if x != nil {
		return x.LastCheck
	}
	return nil
}

type ServerStatusBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Statuses      []*ServerStatus        `protobuf:"bytes,1,rep,name=statuses,proto3" json:"statuses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerStatusBatch) Reset() {
	*x = ServerStatusBatch{}
	mi := &file_pkg_proto_gateway_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerStatusBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerStatusBatch) ProtoMessage() {}

func (x *ServerStatusBatch) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_gateway_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerStatusBatch.ProtoReflect.Descriptor instead.
func (*ServerStatusBatch) Descriptor() ([]byte, []int) {
	return file_pkg_proto_gateway_proto_rawDescGZIP(), []int{14}
}

func (x *ServerStatusBatch) GetStatuses() []*ServerStatus {
	if x != nil {
		return x.Statuses
	}
	return nil
}

type ServerConfigBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Servers       []*Server              `protobuf:"bytes,1,rep,name=servers,proto3" json:"servers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerConfigBatch) Reset() {
	*x = ServerConfigBatch{}
	mi := &file_pkg_proto_gateway_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerConfigBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerConfigBatch) ProtoMessage() {}

func (x *ServerConfigBatch) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_gateway_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerConfigBatch.ProtoReflect.Descriptor instead.
func (*ServerConfigBatch) Descriptor() ([]byte, []int) {
	return file_pkg_proto_gateway_proto_rawDescGZIP(), []int{15}
}

func (x *ServerConfigBatch) GetServers() []*Server {
	if x != nil {
		return x.Servers
	}
	return nil
}

type ShutdownNotification struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Reason         string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	ReconnectDelay *durationpb.Duration   `protobuf:"bytes,2,opt,name=reconnect_delay,json=reconnectDelay,proto3" json:"reconnect_delay,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ShutdownNotification) Reset() {
	*x = ShutdownNotification{}
	mi := &file_pkg_proto_gateway_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownNotification) ProtoMessage() {}

func (x *ShutdownNotification) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_gateway_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownNotification.ProtoReflect.Descriptor instead.
func (*ShutdownNotification) Descriptor() ([]byte, []int) {
	return file_pkg_proto_gateway_proto_rawDescGZIP(), []int{16}
}

func (x *ShutdownNotification) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ShutdownNotification) GetReconnectDelay() *durationpb.Duration {
	if x != nil {
		return x.ReconnectDelay
	}
	return nil
}

type FileReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	MaxSize       int64                  `protobuf:"varint,2,opt,name=max_size,json=maxSize,proto3" json:"max_size,omitempty"`
	Offset        int64                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	Length        int64                  `protobuf:"varint,4,opt,name=length,proto3" json:"length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileReadRequest) Reset() {
	*x = FileReadRequest{}
	mi := &file_pkg_proto_gateway_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileReadRequest) ProtoMessage() {}

func (x *FileReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_gateway_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileReadRequest.ProtoReflect.Descriptor instead.
func (*FileReadRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_gateway_proto_rawDescGZIP(), []int{17}
}

func (x *FileReadRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileReadRequest) GetMaxSize() int64 {
	if x != nil {
		return x.MaxSize
	}
	return 0
}

func (x *FileReadRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *FileReadRequest) GetLength() int64 {
	if x != nil {
		return x.Length
	}
	return 0
}

type FileReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Content       []byte                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	TransferId    string                 `protobuf:"bytes,4,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileReadResponse) Reset() {
	*x = FileReadResponse{}
	mi := &file_pkg_proto_gateway_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileReadResponse) ProtoMessage() {}

func (x *FileReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_gateway_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileReadResponse.ProtoReflect.Descriptor instead.
func (*FileReadResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_gateway_proto_rawDescGZIP(), []int{18}
}

func (x *FileReadResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *FileReadResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *FileReadResponse) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *FileReadResponse) GetTransferId() string {
	if x != nil {
		return x.TransferId
	}
	return ""
}

func (x *FileReadResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type FileWriteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Content       []byte                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Mode          int32                  `protobuf:"varint,3,opt,name=mode,proto3" json:"mode,omitempty"`
	CreateDirs    bool                   `protobuf:"varint,4,opt,name=create_dirs,json=createDirs,proto3" json:"create_dirs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileWriteRequest) Reset() {
	*x = FileWriteRequest{}
	mi := &file_pkg_proto_gateway_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileWriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileWriteRequest) ProtoMessage() {}

func (x *FileWriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_gateway_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileWriteRequest.ProtoReflect.Descriptor instead.
func (*FileWriteRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_gateway_proto_rawDescGZIP(), []int{19}
}

func (x *FileWriteRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileWriteRequest) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *FileWriteRequest) GetMode() int32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *FileWriteRequest) GetCreateDirs() bool {
	if x != nil {
		return x.CreateDirs
	}
	return false
}

type FileWriteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileWriteResponse) Reset() {
	*x = FileWriteResponse{}
	mi := &file_pkg_proto_gateway_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileWriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileWriteResponse) ProtoMessage() {}

func (x *FileWriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_gateway_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileWriteResponse.ProtoReflect.Descriptor instead.
func (*FileWriteResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_gateway_proto_rawDescGZIP(), []int{20}
}

func (x *FileWriteResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *FileWriteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *FileWriteResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type FileListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Recursive     bool                   `protobuf:"varint,2,opt,name=recursive,proto3" json:"recursive,omitempty"`
	Pattern       string                 `protobuf:"bytes,3,opt,name=pattern,proto3" json:"pattern,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileListRequest) Reset() {
	*x = FileListRequest{}
	mi := &file_pkg_proto_gateway_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileListRequest) ProtoMessage() {}

func (x *FileListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_gateway_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileListRequest.ProtoReflect.Descriptor instead.
func (*FileListRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_gateway_proto_rawDescGZIP(), []int{21}
}

func (x *FileListRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileListRequest) GetRecursive() bool {
	if x != nil {
		return x.Recursive
	}
	return false
}

func (x *FileListRequest) GetPattern() string {
	if x != nil {
		return x.Pattern
	}
	return ""
}

type FileListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Files         []*FileStat            `protobuf:"bytes,3,rep,name=files,proto3" json:"files,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileListResponse) Reset() {
	*x = FileListResponse{}
	mi := &file_pkg_proto_gateway_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileListResponse) ProtoMessage() {}

func (x *FileListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_gateway_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileListResponse.ProtoReflect.Descriptor instead.
func (*FileListResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_gateway_proto_rawDescGZIP(), []int{22}
}

func (x *FileListResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *FileListResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *FileListResponse) GetFiles() []*FileStat {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *FileListResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type FileUploadTask struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TransferId     string                 `protobuf:"bytes,1,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	Path           string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	ChecksumSha256 string                 `protobuf:"bytes,3,opt,name=checksum_sha256,json=checksumSha256,proto3" json:"checksum_sha256,omitempty"`
	TotalSize      int64                  `protobuf:"varint,4,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FileUploadTask) Reset() {
	*x = FileUploadTask{}
	mi := &file_pkg_proto_gateway_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileUploadTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileUploadTask) ProtoMessage() {}

func (x *FileUploadTask) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_gateway_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileUploadTask.ProtoReflect.Descriptor instead.
func (*FileUploadTask) Descriptor() ([]byte, []int) {
	return file_pkg_proto_gateway_proto_rawDescGZIP(), []int{23}
}

func (x *FileUploadTask) GetTransferId() string {
	if x != nil {
		return x.TransferId
	}
	return ""
}

func (x *FileUploadTask) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileUploadTask) GetChecksumSha256() string {
	if x != nil {
		return x.ChecksumSha256
	}
	return ""
}

func (x *FileUploadTask) GetTotalSize() int64 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

type FileDownloadTask struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TransferId     string                 `protobuf:"bytes,1,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	Path           string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	ChecksumSha256 string                 `protobuf:"bytes,3,opt,name=checksum_sha256,json=checksumSha256,proto3" json:"checksum_sha256,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FileDownloadTask) Reset() {
	*x = FileDownloadTask{}
	mi := &file_pkg_proto_gateway_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileDownloadTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileDownloadTask) ProtoMessage() {}

func (x *FileDownloadTask) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_gateway_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileDownloadTask.ProtoReflect.Descriptor instead.
func (*FileDownloadTask) Descriptor() ([]byte, []int) {
	return file_pkg_proto_gateway_proto_rawDescGZIP(), []int{24}
}

func (x *FileDownloadTask) GetTransferId() string {
	if x != nil {
		return x.TransferId
	}
	return ""
}

func (x *FileDownloadTask) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileDownloadTask) GetChecksumSha256() string {
	if x != nil {
		return x.ChecksumSha256
	}
	return ""
}

type EnrollRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SetupKey      string                 `protobuf:"bytes,1,opt,name=setup_key,json=setupKey,proto3" json:"setup_key,omitempty"`
	Host          string                 `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Port          int32                  `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	Os            string                 `protobuf:"bytes,4,opt,name=os,proto3" json:"os,omitempty"`
	Version       string                 `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	Capabilities  []string               `protobuf:"bytes,6,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollRequest) Reset() {
	*x = EnrollRequest{}
	mi := &file_pkg_proto_gateway_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollRequest) ProtoMessage() {}

func (x *EnrollRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_gateway_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollRequest.ProtoReflect.Descriptor instead.
func (*EnrollRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_gateway_proto_rawDescGZIP(), []int{25}
}

func (x *EnrollRequest) GetSetupKey() string {
	if x != nil {
		return x.SetupKey
	}
	return ""
}

func (x *EnrollRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *EnrollRequest) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *EnrollRequest) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *EnrollRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *EnrollRequest) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type EnrollResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Success           bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage      string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	NodeId            uint64                 `protobuf:"varint,3,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	ApiKey            string                 `protobuf:"bytes,4,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	RootCertificate   string                 `protobuf:"bytes,5,opt,name=root_certificate,json=rootCertificate,proto3" json:"root_certificate,omitempty"`
	ServerCertificate string                 `protobuf:"bytes,6,opt,name=server_certificate,json=serverCertificate,proto3" json:"server_certificate,omitempty"`
	ServerPrivateKey  string                 `protobuf:"bytes,7,opt,name=server_private_key,json=serverPrivateKey,proto3" json:"server_private_key,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *EnrollResponse) Reset() {
	*x = EnrollResponse{}
	mi := &file_pkg_proto_gateway_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollResponse) ProtoMessage() {}

func (x *EnrollResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_gateway_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollResponse.ProtoReflect.Descriptor instead.
func (*EnrollResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_gateway_proto_rawDescGZIP(), []int{26}
}

func (x *EnrollResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *EnrollResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *EnrollResponse) GetNodeId() uint64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *EnrollResponse) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *EnrollResponse) GetRootCertificate() string {
	if x != nil {
		return x.RootCertificate
	}
	return ""
}

func (x *EnrollResponse) GetServerCertificate() string {
	if x != nil {
		return x.ServerCertificate
	}
	return ""
}

func (x *EnrollResponse) GetServerPrivateKey() string {
	if x != nil {
		return x.ServerPrivateKey
	}
	return ""
}

type AttachRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ServerId      uint64                 `protobuf:"varint,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachRequest) Reset() {
	*x = AttachRequest{}
	mi := &file_pkg_proto_gateway_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachRequest) ProtoMessage() {}

func (x *AttachRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_gateway_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachRequest.ProtoReflect.Descriptor instead.
func (*AttachRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_gateway_proto_rawDescGZIP(), []int{27}
}

func (x *AttachRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AttachRequest) GetServerId() uint64 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

type AttachStarted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ServerId      uint64                 `protobuf:"varint,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachStarted) Reset() {
	*x = AttachStarted{}
	mi := &file_pkg_proto_gateway_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachStarted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachStarted) ProtoMessage() {}

func (x *AttachStarted) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_gateway_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachStarted.ProtoReflect.Descriptor instead.
func (*AttachStarted) Descriptor() ([]byte, []int) {
	return file_pkg_proto_gateway_proto_rawDescGZIP(), []int{28}
}

func (x *AttachStarted) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AttachStarted) GetServerId() uint64 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

type AttachInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachInput) Reset() {
	*x = AttachInput{}
	mi := &file_pkg_proto_gateway_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachInput) ProtoMessage() {}

func (x *AttachInput) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_gateway_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachInput.ProtoReflect.Descriptor instead.
func (*AttachInput) Descriptor() ([]byte, []int) {
	return file_pkg_proto_gateway_proto_rawDescGZIP(), []int{29}
}

func (x *AttachInput) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AttachInput) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type AttachOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachOutput) Reset() {
	*x = AttachOutput{}
	mi := &file_pkg_proto_gateway_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachOutput) ProtoMessage() {}

func (x *AttachOutput) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_gateway_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachOutput.ProtoReflect.Descriptor instead.
func (*AttachOutput) Descriptor() ([]byte, []int) {
	return file_pkg_proto_gateway_proto_rawDescGZIP(), []int{30}
}

func (x *AttachOutput) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AttachOutput) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type AttachDetach struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachDetach) Reset() {
	*x = AttachDetach{}
	mi := &file_pkg_proto_gateway_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachDetach) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachDetach) ProtoMessage() {}

func (x *AttachDetach) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_gateway_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachDetach.ProtoReflect.Descriptor instead.
func (*AttachDetach) Descriptor() ([]byte, []int) {
	return file_pkg_proto_gateway_proto_rawDescGZIP(), []int{31}
}

func (x *AttachDetach) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AttachDetach) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type AttachClosed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	ExitCode      int32                  `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachClosed) Reset() {
	*x = AttachClosed{}
	mi := &file_pkg_proto_gateway_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachClosed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachClosed) ProtoMessage() {}

func (x *AttachClosed) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_gateway_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachClosed.ProtoReflect.Descriptor instead.
func (*AttachClosed) Descriptor() ([]byte, []int) {
	return file_pkg_proto_gateway_proto_rawDescGZIP(), []int{32}
}

func (x *AttachClosed) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AttachClosed) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *AttachClosed) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_pkg_proto_gateway_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_gateway_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_gateway_proto_rawDescGZIP(), []int{33}
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	BuildDate     string                 `protobuf:"bytes,4,opt,name=build_date,json=buildDate,proto3" json:"build_date,omitempty"`
	UptimeSeconds int64                  `protobuf:"varint,5,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	WorkingTasks  int32                  `protobuf:"varint,6,opt,name=working_tasks,json=workingTasks,proto3" json:"working_tasks,omitempty"`
	WaitingTasks  int32                  `protobuf:"varint,7,opt,name=waiting_tasks,json=waitingTasks,proto3" json:"waiting_tasks,omitempty"`
	OnlineServers int32                  `protobuf:"varint,8,opt,name=online_servers,json=onlineServers,proto3" json:"online_servers,omitempty"`
	Error         string                 `protobuf:"bytes,9,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_pkg_proto_gateway_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_gateway_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_gateway_proto_rawDescGZIP(), []int{34}
}

func (x *StatusResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *StatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StatusResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *StatusResponse) GetBuildDate() string {
	if x != nil {
		return x.BuildDate
	}
	return ""
}

func (x *StatusResponse) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *StatusResponse) GetWorkingTasks() int32 {
	if x != nil {
		return x.WorkingTasks
	}
	return 0
}

func (x *StatusResponse) GetWaitingTasks() int32 {
	if x != nil {
		return x.WaitingTasks
	}
	return 0
}

func (x *StatusResponse) GetOnlineServers() int32 {
	if x != nil {
		return x.OnlineServers
	}
	return 0
}

func (x *StatusResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_pkg_proto_gateway_proto protoreflect.FileDescriptor

const file_pkg_proto_gateway_proto_rawDesc = "" +
	"\n" +
	"\x17pkg/proto/gateway.proto\x12\x06gameap\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1apkg/proto/daemontask.proto\x1a\x16pkg/proto/server.proto\x1a\x14pkg/proto/game.proto\x1a\x17pkg/proto/gamemod.proto\x1a\x1cpkg/proto/filetransfer.proto\"\x94\b\n" +
	"\rDaemonMessage\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x125\n" +
	"\bregister\x18\n" +
	" \x01(\v2\x17.gameap.RegisterRequestH\x00R\bregister\x121\n" +
	"\theartbeat\x18\v \x01(\v2\x11.gameap.HeartbeatH\x00R\theartbeat\x12;\n" +
	"\vtask_status\x18\x14 \x01(\v2\x18.gameap.TaskStatusUpdateH\x00R\n" +
	"taskStatus\x125\n" +
	"\vtask_output\x18\x15 \x01(\v2\x12.gameap.TaskOutputH\x00R\n" +
	"taskOutput\x12>\n" +
	"\x0ecommand_output\x18\x1e \x01(\v2\x15.gameap.CommandOutputH\x00R\rcommandOutput\x12>\n" +
	"\x0ecommand_result\x18\x1f \x01(\v2\x15.gameap.CommandResultH\x00R\rcommandResult\x12>\n" +
	"\x0eattach_started\x18  \x01(\v2\x15.gameap.AttachStartedH\x00R\rattachStarted\x12;\n" +
	"\rattach_output\x18! \x01(\v2\x14.gameap.AttachOutputH\x00R\fattachOutput\x12;\n" +
	"\rattach_closed\x18\" \x01(\v2\x14.gameap.AttachClosedH\x00R\fattachClosed\x12D\n" +
	"\x0fserver_statuses\x182 \x01(\v2\x19.gameap.ServerStatusBatchH\x00R\x0eserverStatuses\x12H\n" +
	"\x12file_read_response\x18< \x01(\v2\x18.gameap.FileReadResponseH\x00R\x10fileReadResponse\x12K\n" +
	"\x13file_write_response\x18= \x01(\v2\x19.gameap.FileWriteResponseH\x00R\x11fileWriteResponse\x12H\n" +
	"\x12file_list_response\x18> \x01(\v2\x18.gameap.FileListResponseH\x00R\x10fileListResponse\x12W\n" +
	"\x17file_operation_response\x18? \x01(\v2\x1d.gameap.FileOperationResponseH\x00R\x15fileOperationResponse\x12A\n" +
	"\x0fstatus_response\x18F \x01(\v2\x16.gameap.StatusResponseH\x00R\x0estatusResponseB\t\n" +
	"\apayload\"\xc0\b\n" +
	"\x0eGatewayMessage\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x128\n" +
	"\fregister_ack\x18\n" +
	" \x01(\v2\x13.gameap.RegisterAckH\x00R\vregisterAck\x12:\n" +
	"\bshutdown\x18\v \x01(\v2\x1c.gameap.ShutdownNotificationH\x00R\bshutdown\x12(\n" +
	"\x04task\x18\x14 \x01(\v2\x12.gameap.DaemonTaskH\x00R\x04task\x125\n" +
	"\vtask_cancel\x18\x15 \x01(\v2\x12.gameap.TaskCancelH\x00R\n" +
	"taskCancel\x122\n" +
	"\acommand\x18\x1e \x01(\v2\x16.gameap.CommandRequestH\x00R\acommand\x12>\n" +
	"\x0eattach_request\x18\" \x01(\v2\x15.gameap.AttachRequestH\x00R\rattachRequest\x128\n" +
	"\fattach_input\x18# \x01(\v2\x13.gameap.AttachInputH\x00R\vattachInput\x12;\n" +
	"\rattach_detach\x18$ \x01(\v2\x14.gameap.AttachDetachH\x00R\fattachDetach\x125\n" +
	"\rserver_config\x182 \x01(\v2\x0e.gameap.ServerH\x00R\fserverConfig\x12K\n" +
	"\x13server_config_batch\x183 \x01(\v2\x19.gameap.ServerConfigBatchH\x00R\x11serverConfigBatch\x126\n" +
	"\tfile_read\x18< \x01(\v2\x17.gameap.FileReadRequestH\x00R\bfileRead\x129\n" +
	"\n" +
	"file_write\x18= \x01(\v2\x18.gameap.FileWriteRequestH\x00R\tfileWrite\x126\n" +
	"\tfile_list\x18> \x01(\v2\x17.gameap.FileListRequestH\x00R\bfileList\x12B\n" +
	"\x10file_upload_task\x18? \x01(\v2\x16.gameap.FileUploadTaskH\x00R\x0efileUploadTask\x12E\n" +
	"\x0efile_operation\x18@ \x01(\v2\x1c.gameap.FileOperationRequestH\x00R\rfileOperation\x12H\n" +
	"\x12file_download_task\x18A \x01(\v2\x18.gameap.FileDownloadTaskH\x00R\x10fileDownloadTask\x12>\n" +
	"\x0estatus_request\x18F \x01(\v2\x15.gameap.StatusRequestH\x00R\rstatusRequestB\t\n" +
	"\apayload\"\xbf\x01\n" +
	"\x0fRegisterRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\x04R\x06nodeId\x12\x17\n" +
	"\aapi_key\x18\x02 \x01(\tR\x06apiKey\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\"\n" +
	"\fcapabilities\x18\x04 \x03(\tR\fcapabilities\x12<\n" +
	"\x0fin_flight_tasks\x18\x05 \x03(\v2\x14.gameap.InFlightTaskR\rinFlightTasks\"\xbb\x01\n" +
	"\fInFlightTask\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x04R\x06taskId\x120\n" +
	"\x06status\x18\x02 \x01(\x0e2\x18.gameap.DaemonTaskStatusR\x06status\x12%\n" +
	"\x0epartial_output\x18\x03 \x01(\tR\rpartialOutput\x129\n" +
	"\n" +
	"started_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\"\xcb\x02\n" +
	"\vRegisterAck\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12(\n" +
	"\aservers\x18\x03 \x03(\v2\x0e.gameap.ServerR\aservers\x127\n" +
	"\rpending_tasks\x18\x04 \x03(\v2\x12.gameap.DaemonTaskR\fpendingTasks\x12\"\n" +
	"\x05games\x18\x05 \x03(\v2\f.gameap.GameR\x05games\x12,\n" +
	"\tgame_mods\x18\x06 \x03(\v2\x0f.gameap.GameModR\bgameMods\x12H\n" +
	"\x12heartbeat_interval\x18\a \x01(\v2\x19.google.protobuf.DurationR\x11heartbeatInterval\"}\n" +
	"\tHeartbeat\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x126\n" +
	"\fsystem_stats\x18\x02 \x01(\v2\x13.gameap.SystemStatsR\vsystemStats\"\x8d\x02\n" +
	"\vSystemStats\x12&\n" +
	"\x0fload_average_1m\x18\x01 \x01(\x01R\rloadAverage1m\x12&\n" +
	"\x0fload_average_5m\x18\x02 \x01(\x01R\rloadAverage5m\x12(\n" +
	"\x10load_average_15m\x18\x03 \x01(\x01R\x0eloadAverage15m\x12*\n" +
	"\x11cpu_usage_percent\x18\x04 \x01(\x01R\x0fcpuUsagePercent\x12*\n" +
	"\x11memory_used_bytes\x18\x05 \x01(\x04R\x0fmemoryUsedBytes\x12,\n" +
	"\x12memory_total_bytes\x18\x06 \x01(\x04R\x10memoryTotalBytes\"w\n" +
	"\x10TaskStatusUpdate\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x04R\x06taskId\x120\n" +
	"\x06status\x18\x02 \x01(\x0e2\x18.gameap.DaemonTaskStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"c\n" +
	"\n" +
	"TaskOutput\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x04R\x06taskId\x12!\n" +
	"\foutput_chunk\x18\x02 \x01(\fR\voutputChunk\x12\x19\n" +
	"\bis_final\x18\x03 \x01(\bR\aisFinal\"=\n" +
	"\n" +
	"TaskCancel\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x04R\x06taskId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\xdb\x01\n" +
	"\x0eCommandRequest\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x1b\n" +
	"\tserver_id\x18\x02 \x01(\x04R\bserverId\x12\x18\n" +
	"\acommand\x18\x03 \x01(\tR\acommand\x123\n" +
	"\atimeout\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\atimeout\x12#\n" +
	"\rstream_output\x18\x05 \x01(\bR\fstreamOutput\x12\x19\n" +
	"\bwork_dir\x18\x06 \x01(\tR\aworkDir\"Q\n" +
	"\rCommandOutput\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12!\n" +
	"\foutput_chunk\x18\x02 \x01(\fR\voutputChunk\"\x98\x01\n" +
	"\rCommandResult\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x1b\n" +
	"\texit_code\x18\x02 \x01(\x05R\bexitCode\x12\x16\n" +
	"\x06output\x18\x03 \x01(\fR\x06output\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\x12\x1d\n" +
	"\n" +
	"request_id\x18\x05 \x01(\tR\trequestId\"\x85\x01\n" +
	"\fServerStatus\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\x04R\bserverId\x12\x1d\n" +
	"\n" +
	"is_running\x18\x02 \x01(\bR\tisRunning\x129\n" +
	"\n" +
	"last_check\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tlastCheck\"E\n" +
	"\x11ServerStatusBatch\x120\n" +
	"\bstatuses\x18\x01 \x03(\v2\x14.gameap.ServerStatusR\bstatuses\"=\n" +
	"\x11ServerConfigBatch\x12(\n" +
	"\aservers\x18\x01 \x03(\v2\x0e.gameap.ServerR\aservers\"r\n" +
	"\x14ShutdownNotification\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\x12B\n" +
	"\x0freconnect_delay\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\x0ereconnectDelay\"p\n" +
	"\x0fFileReadRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x19\n" +
	"\bmax_size\x18\x02 \x01(\x03R\amaxSize\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x03R\x06offset\x12\x16\n" +
	"\x06length\x18\x04 \x01(\x03R\x06length\"\x9c\x01\n" +
	"\x10FileReadResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\acontent\x18\x03 \x01(\fR\acontent\x12\x1f\n" +
	"\vtransfer_id\x18\x04 \x01(\tR\n" +
	"transferId\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\"u\n" +
	"\x10FileWriteRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\x12\x12\n" +
	"\x04mode\x18\x03 \x01(\x05R\x04mode\x12\x1f\n" +
	"\vcreate_dirs\x18\x04 \x01(\bR\n" +
	"createDirs\"b\n" +
	"\x11FileWriteResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"]\n" +
	"\x0fFileListRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1c\n" +
	"\trecursive\x18\x02 \x01(\bR\trecursive\x12\x18\n" +
	"\apattern\x18\x03 \x01(\tR\apattern\"\x89\x01\n" +
	"\x10FileListResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12&\n" +
	"\x05files\x18\x03 \x03(\v2\x10.gameap.FileStatR\x05files\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"\x8d\x01\n" +
	"\x0eFileUploadTask\x12\x1f\n" +
	"\vtransfer_id\x18\x01 \x01(\tR\n" +
	"transferId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12'\n" +
	"\x0fchecksum_sha256\x18\x03 \x01(\tR\x0echecksumSha256\x12\x1d\n" +
	"\n" +
	"total_size\x18\x04 \x01(\x03R\ttotalSize\"p\n" +
	"\x10FileDownloadTask\x12\x1f\n" +
	"\vtransfer_id\x18\x01 \x01(\tR\n" +
	"transferId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12'\n" +
	"\x0fchecksum_sha256\x18\x03 \x01(\tR\x0echecksumSha256\"\xa2\x01\n" +
	"\rEnrollRequest\x12\x1b\n" +
	"\tsetup_key\x18\x01 \x01(\tR\bsetupKey\x12\x12\n" +
	"\x04host\x18\x02 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x05R\x04port\x12\x0e\n" +
	"\x02os\x18\x04 \x01(\tR\x02os\x12\x18\n" +
	"\aversion\x18\x05 \x01(\tR\aversion\x12\"\n" +
	"\fcapabilities\x18\x06 \x03(\tR\fcapabilities\"\x89\x02\n" +
	"\x0eEnrollResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12\x17\n" +
	"\anode_id\x18\x03 \x01(\x04R\x06nodeId\x12\x17\n" +
	"\aapi_key\x18\x04 \x01(\tR\x06apiKey\x12)\n" +
	"\x10root_certificate\x18\x05 \x01(\tR\x0frootCertificate\x12-\n" +
	"\x12server_certificate\x18\x06 \x01(\tR\x11serverCertificate\x12,\n" +
	"\x12server_private_key\x18\a \x01(\tR\x10serverPrivateKey\"K\n" +
	"\rAttachRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1b\n" +
	"\tserver_id\x18\x02 \x01(\x04R\bserverId\"K\n" +
	"\rAttachStarted\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1b\n" +
	"\tserver_id\x18\x02 \x01(\x04R\bserverId\"@\n" +
	"\vAttachInput\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"A\n" +
	"\fAttachOutput\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"E\n" +
	"\fAttachDetach\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"b\n" +
	"\fAttachClosed\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x1b\n" +
	"\texit_code\x18\x03 \x01(\x05R\bexitCode\"\x0f\n" +
	"\rStatusRequest\"\xb0\x02\n" +
	"\x0eStatusResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x1d\n" +
	"\n" +
	"build_date\x18\x04 \x01(\tR\tbuildDate\x12%\n" +
	"\x0euptime_seconds\x18\x05 \x01(\x03R\ruptimeSeconds\x12#\n" +
	"\rworking_tasks\x18\x06 \x01(\x05R\fworkingTasks\x12#\n" +
	"\rwaiting_tasks\x18\a \x01(\x05R\fwaitingTasks\x12%\n" +
	"\x0eonline_servers\x18\b \x01(\x05R\ronlineServers\x12\x14\n" +
	"\x05error\x18\t \x01(\tR\x05error2\x86\x01\n" +
	"\rDaemonGateway\x12<\n" +
	"\aConnect\x12\x15.gameap.DaemonMessage\x1a\x16.gameap.GatewayMessage(\x010\x01\x127\n" +
	"\x06Enroll\x12\x15.gameap.EnrollRequest\x1a\x16.gameap.EnrollResponseB$Z\"github.com/gameap/gameap/pkg/protob\x06proto3"

var (
	file_pkg_proto_gateway_proto_rawDescOnce sync.Once
	file_pkg_proto_gateway_proto_rawDescData []byte
)

func file_pkg_proto_gateway_proto_rawDescGZIP() []byte {
	file_pkg_proto_gateway_proto_rawDescOnce.Do(func() {
		file_pkg_proto_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_gateway_proto_rawDesc), len(file_pkg_proto_gateway_proto_rawDesc)))
	})
	return file_pkg_proto_gateway_proto_rawDescData
}

var file_pkg_proto_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 35)
var file_pkg_proto_gateway_proto_goTypes = []any{
	(*DaemonMessage)(nil),         // 0: gameap.DaemonMessage
	(*GatewayMessage)(nil),        // 1: gameap.GatewayMessage
	(*RegisterRequest)(nil),       // 2: gameap.RegisterRequest
	(*InFlightTask)(nil),          // 3: gameap.InFlightTask
	(*RegisterAck)(nil),           // 4: gameap.RegisterAck
	(*Heartbeat)(nil),             // 5: gameap.Heartbeat
	(*SystemStats)(nil),           // 6: gameap.SystemStats
	(*TaskStatusUpdate)(nil),      // 7: gameap.TaskStatusUpdate
	(*TaskOutput)(nil),            // 8: gameap.TaskOutput
	(*TaskCancel)(nil),            // 9: gameap.TaskCancel
	(*CommandRequest)(nil),        // 10: gameap.CommandRequest
	(*CommandOutput)(nil),         // 11: gameap.CommandOutput
	(*CommandResult)(nil),         // 12: gameap.CommandResult
	(*ServerStatus)(nil),          // 13: gameap.ServerStatus
	(*ServerStatusBatch)(nil),     // 14: gameap.ServerStatusBatch
	(*ServerConfigBatch)(nil),     // 15: gameap.ServerConfigBatch
	(*ShutdownNotification)(nil),  // 16: gameap.ShutdownNotification
	(*FileReadRequest)(nil),       // 17: gameap.FileReadRequest
	(*FileReadResponse)(nil),      // 18: gameap.FileReadResponse
	(*FileWriteRequest)(nil),      // 19: gameap.FileWriteRequest
	(*FileWriteResponse)(nil),     // 20: gameap.FileWriteResponse
	(*FileListRequest)(nil),       // 21: gameap.FileListRequest
	(*FileListResponse)(nil),      // 22: gameap.FileListResponse
	(*FileUploadTask)(nil),        // 23: gameap.FileUploadTask
	(*FileDownloadTask)(nil),      // 24: gameap.FileDownloadTask
	(*EnrollRequest)(nil),         // 25: gameap.EnrollRequest
	(*EnrollResponse)(nil),        // 26: gameap.EnrollResponse
	(*AttachRequest)(nil),         // 27: gameap.AttachRequest
	(*AttachStarted)(nil),         // 28: gameap.AttachStarted
	(*AttachInput)(nil),           // 29: gameap.AttachInput
	(*AttachOutput)(nil),          // 30: gameap.AttachOutput
	(*AttachDetach)(nil),          // 31: gameap.AttachDetach
	(*AttachClosed)(nil),          // 32: gameap.AttachClosed
	(*StatusRequest)(nil),         // 33: gameap.StatusRequest
	(*StatusResponse)(nil),        // 34: gameap.StatusResponse
	(*FileOperationResponse)(nil), // 35: gameap.FileOperationResponse
	(*DaemonTask)(nil),            // 36: gameap.DaemonTask
	(*Server)(nil),                // 37: gameap.Server
	(*FileOperationRequest)(nil),  // 38: gameap.FileOperationRequest
	(DaemonTaskStatus)(0),         // 39: gameap.DaemonTaskStatus
	(*timestamppb.Timestamp)(nil), // 40: google.protobuf.Timestamp
	(*Game)(nil),                  // 41: gameap.Game
	(*GameMod)(nil),               // 42: gameap.GameMod
	(*durationpb.Duration)(nil),   // 43: google.protobuf.Duration
	(*FileStat)(nil),              // 44: gameap.FileStat
}
var file_pkg_proto_gateway_proto_depIdxs = []int32{
	2,  // 0: gameap.DaemonMessage.register:type_name -> gameap.RegisterRequest
	5,  // 1: gameap.DaemonMessage.heartbeat:type_name -> gameap.Heartbeat
	7,  // 2: gameap.DaemonMessage.task_status:type_name -> gameap.TaskStatusUpdate
	8,  // 3: gameap.DaemonMessage.task_output:type_name -> gameap.TaskOutput
	11, // 4: gameap.DaemonMessage.command_output:type_name -> gameap.CommandOutput
	12, // 5: gameap.DaemonMessage.command_result:type_name -> gameap.CommandResult
	28, // 6: gameap.DaemonMessage.attach_started:type_name -> gameap.AttachStarted
	30, // 7: gameap.DaemonMessage.attach_output:type_name -> gameap.AttachOutput
	32, // 8: gameap.DaemonMessage.attach_closed:type_name -> gameap.AttachClosed
	14, // 9: gameap.DaemonMessage.server_statuses:type_name -> gameap.ServerStatusBatch
	18, // 10: gameap.DaemonMessage.file_read_response:type_name -> gameap.FileReadResponse
	20, // 11: gameap.DaemonMessage.file_write_response:type_name -> gameap.FileWriteResponse
	22, // 12: gameap.DaemonMessage.file_list_response:type_name -> gameap.FileListResponse
	35, // 13: gameap.DaemonMessage.file_operation_response:type_name -> gameap.FileOperationResponse
	34, // 14: gameap.DaemonMessage.status_response:type_name -> gameap.StatusResponse
	4,  // 15: gameap.GatewayMessage.register_ack:type_name -> gameap.RegisterAck
	16, // 16: gameap.GatewayMessage.shutdown:type_name -> gameap.ShutdownNotification
	36, // 17: gameap.GatewayMessage.task:type_name -> gameap.DaemonTask
	9,  // 18: gameap.GatewayMessage.task_cancel:type_name -> gameap.TaskCancel
	10, // 19: gameap.GatewayMessage.command:type_name -> gameap.CommandRequest
	27, // 20: gameap.GatewayMessage.attach_request:type_name -> gameap.AttachRequest
	29, // 21: gameap.GatewayMessage.attach_input:type_name -> gameap.AttachInput
	31, // 22: gameap.GatewayMessage.attach_detach:type_name -> gameap.AttachDetach
	37, // 23: gameap.GatewayMessage.server_config:type_name -> gameap.Server
	15, // 24: gameap.GatewayMessage.server_config_batch:type_name -> gameap.ServerConfigBatch
	17, // 25: gameap.GatewayMessage.file_read:type_name -> gameap.FileReadRequest
	19, // 26: gameap.GatewayMessage.file_write:type_name -> gameap.FileWriteRequest
	21, // 27: gameap.GatewayMessage.file_list:type_name -> gameap.FileListRequest
	23, // 28: gameap.GatewayMessage.file_upload_task:type_name -> gameap.FileUploadTask
	38, // 29: gameap.GatewayMessage.file_operation:type_name -> gameap.FileOperationRequest
	24, // 30: gameap.GatewayMessage.file_download_task:type_name -> gameap.FileDownloadTask
	33, // 31: gameap.GatewayMessage.status_request:type_name -> gameap.StatusRequest
	3,  // 32: gameap.RegisterRequest.in_flight_tasks:type_name -> gameap.InFlightTask
	39, // 33: gameap.InFlightTask.status:type_name -> gameap.DaemonTaskStatus
	40, // 34: gameap.InFlightTask.started_at:type_name -> google.protobuf.Timestamp
	37, // 35: gameap.RegisterAck.servers:type_name -> gameap.Server
	36, // 36: gameap.RegisterAck.pending_tasks:type_name -> gameap.DaemonTask
	41, // 37: gameap.RegisterAck.games:type_name -> gameap.Game
	42, // 38: gameap.RegisterAck.game_mods:type_name -> gameap.GameMod
	43, // 39: gameap.RegisterAck.heartbeat_interval:type_name -> google.protobuf.Duration
	40, // 40: gameap.Heartbeat.timestamp:type_name -> google.protobuf.Timestamp
	6,  // 41: gameap.Heartbeat.system_stats:type_name -> gameap.SystemStats
	39, // 42: gameap.TaskStatusUpdate.status:type_name -> gameap.DaemonTaskStatus
	43, // 43: gameap.CommandRequest.timeout:type_name -> google.protobuf.Duration
	40, // 44: gameap.ServerStatus.last_check:type_name -> google.protobuf.Timestamp
	13, // 45: gameap.ServerStatusBatch.statuses:type_name -> gameap.ServerStatus
	37, // 46: gameap.ServerConfigBatch.servers:type_name -> gameap.Server
	43, // 47: gameap.ShutdownNotification.reconnect_delay:type_name -> google.protobuf.Duration
	44, // 48: gameap.FileListResponse.files:type_name -> gameap.FileStat
	0,  // 49: gameap.DaemonGateway.Connect:input_type -> gameap.DaemonMessage
	25, // 50: gameap.DaemonGateway.Enroll:input_type -> gameap.EnrollRequest
	1,  // 51: gameap.DaemonGateway.Connect:output_type -> gameap.GatewayMessage
	26, // 52: gameap.DaemonGateway.Enroll:output_type -> gameap.EnrollResponse
	51, // [51:53] is the sub-list for method output_type
	49, // [49:51] is the sub-list for method input_type
	49, // [49:49] is the sub-list for extension type_name
	49, // [49:49] is the sub-list for extension extendee
	0,  // [0:49] is the sub-list for field type_name
}

func init() { file_pkg_proto_gateway_proto_init() }
func file_pkg_proto_gateway_proto_init() {
	if File_pkg_proto_gateway_proto != nil {
		return
	}
	file_pkg_proto_daemontask_proto_init()
	file_pkg_proto_server_proto_init()
	file_pkg_proto_game_proto_init()
	file_pkg_proto_gamemod_proto_init()
	file_pkg_proto_filetransfer_proto_init()
	file_pkg_proto_gateway_proto_msgTypes[0].OneofWrappers = []any{
		(*DaemonMessage_Register)(nil),
		(*DaemonMessage_Heartbeat)(nil),
		(*DaemonMessage_TaskStatus)(nil),
		(*DaemonMessage_TaskOutput)(nil),
		(*DaemonMessage_CommandOutput)(nil),
		(*DaemonMessage_CommandResult)(nil),
		(*DaemonMessage_AttachStarted)(nil),
		(*DaemonMessage_AttachOutput)(nil),
		(*DaemonMessage_AttachClosed)(nil),
		(*DaemonMessage_ServerStatuses)(nil),
		(*DaemonMessage_FileReadResponse)(nil),
		(*DaemonMessage_FileWriteResponse)(nil),
		(*DaemonMessage_FileListResponse)(nil),
		(*DaemonMessage_FileOperationResponse)(nil),
		(*DaemonMessage_StatusResponse)(nil),
	}
	file_pkg_proto_gateway_proto_msgTypes[1].OneofWrappers = []any{
		(*GatewayMessage_RegisterAck)(nil),
		(*GatewayMessage_Shutdown)(nil),
		(*GatewayMessage_Task)(nil),
		(*GatewayMessage_TaskCancel)(nil),
		(*GatewayMessage_Command)(nil),
		(*GatewayMessage_AttachRequest)(nil),
		(*GatewayMessage_AttachInput)(nil),
		(*GatewayMessage_AttachDetach)(nil),
		(*GatewayMessage_ServerConfig)(nil),
		(*GatewayMessage_ServerConfigBatch)(nil),
		(*GatewayMessage_FileRead)(nil),
		(*GatewayMessage_FileWrite)(nil),
		(*GatewayMessage_FileList)(nil),
		(*GatewayMessage_FileUploadTask)(nil),
		(*GatewayMessage_FileOperation)(nil),
		(*GatewayMessage_FileDownloadTask)(nil),
		(*GatewayMessage_StatusRequest)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_gateway_proto_rawDesc), len(file_pkg_proto_gateway_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   35,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_gateway_proto_goTypes,
		DependencyIndexes: file_pkg_proto_gateway_proto_depIdxs,
		MessageInfos:      file_pkg_proto_gateway_proto_msgTypes,
	}.Build()
	File_pkg_proto_gateway_proto = out.File
	file_pkg_proto_gateway_proto_goTypes = nil
	file_pkg_proto_gateway_proto_depIdxs = nil
}
