// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.3
// source: pkg/proto/gateway.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DaemonGateway_Connect_FullMethodName = "/gameap.DaemonGateway/Connect"
	DaemonGateway_Enroll_FullMethodName  = "/gameap.DaemonGateway/Enroll"
)

// DaemonGatewayClient is the client API for DaemonGateway service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DaemonGatewayClient interface {
	Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[DaemonMessage, GatewayMessage], error)
	Enroll(ctx context.Context, in *EnrollRequest, opts ...grpc.CallOption) (*EnrollResponse, error)
}

type daemonGatewayClient struct {
	cc grpc.ClientConnInterface
}

func NewDaemonGatewayClient(cc grpc.ClientConnInterface) DaemonGatewayClient {
	return &daemonGatewayClient{cc}
}

func (c *daemonGatewayClient) Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[DaemonMessage, GatewayMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DaemonGateway_ServiceDesc.Streams[0], DaemonGateway_Connect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DaemonMessage, GatewayMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DaemonGateway_ConnectClient = grpc.BidiStreamingClient[DaemonMessage, GatewayMessage]

func (c *daemonGatewayClient) Enroll(ctx context.Context, in *EnrollRequest, opts ...grpc.CallOption) (*EnrollResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnrollResponse)
	err := c.cc.Invoke(ctx, DaemonGateway_Enroll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DaemonGatewayServer is the server API for DaemonGateway service.
// All implementations must embed UnimplementedDaemonGatewayServer
// for forward compatibility.
type DaemonGatewayServer interface {
	Connect(grpc.BidiStreamingServer[DaemonMessage, GatewayMessage]) error
	Enroll(context.Context, *EnrollRequest) (*EnrollResponse, error)
	mustEmbedUnimplementedDaemonGatewayServer()
}

// UnimplementedDaemonGatewayServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDaemonGatewayServer struct{}

func (UnimplementedDaemonGatewayServer) Connect(grpc.BidiStreamingServer[DaemonMessage, GatewayMessage]) error {
	return status.Error(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedDaemonGatewayServer) Enroll(context.Context, *EnrollRequest) (*EnrollResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Enroll not implemented")
}
func (UnimplementedDaemonGatewayServer) mustEmbedUnimplementedDaemonGatewayServer() {}
func (UnimplementedDaemonGatewayServer) testEmbeddedByValue()                       {}

// UnsafeDaemonGatewayServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DaemonGatewayServer will
// result in compilation errors.
type UnsafeDaemonGatewayServer interface {
	mustEmbedUnimplementedDaemonGatewayServer()
}

func RegisterDaemonGatewayServer(s grpc.ServiceRegistrar, srv DaemonGatewayServer) {
	// If the following call panics, it indicates UnimplementedDaemonGatewayServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DaemonGateway_ServiceDesc, srv)
}

func _DaemonGateway_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DaemonGatewayServer).Connect(&grpc.GenericServerStream[DaemonMessage, GatewayMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DaemonGateway_ConnectServer = grpc.BidiStreamingServer[DaemonMessage, GatewayMessage]

func _DaemonGateway_Enroll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnrollRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonGatewayServer).Enroll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonGateway_Enroll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonGatewayServer).Enroll(ctx, req.(*EnrollRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DaemonGateway_ServiceDesc is the grpc.ServiceDesc for DaemonGateway service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DaemonGateway_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gameap.DaemonGateway",
	HandlerType: (*DaemonGatewayServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Enroll",
			Handler:    _DaemonGateway_Enroll_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _DaemonGateway_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "pkg/proto/gateway.proto",
}
