// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: pkg/proto/pat.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PersonalAccessToken struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TokenableType EntityType             `protobuf:"varint,2,opt,name=tokenable_type,json=tokenableType,proto3,enum=gameap.EntityType" json:"tokenable_type,omitempty"`
	TokenableId   uint64                 `protobuf:"varint,3,opt,name=tokenable_id,json=tokenableId,proto3" json:"tokenable_id,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Abilities     []string               `protobuf:"bytes,5,rep,name=abilities,proto3" json:"abilities,omitempty"`
	LastUsedAt    *int64                 `protobuf:"varint,6,opt,name=last_used_at,json=lastUsedAt,proto3,oneof" json:"last_used_at,omitempty"`
	CreatedAt     *int64                 `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3,oneof" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PersonalAccessToken) Reset() {
	*x = PersonalAccessToken{}
	mi := &file_pkg_proto_pat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PersonalAccessToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersonalAccessToken) ProtoMessage() {}

func (x *PersonalAccessToken) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_pat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersonalAccessToken.ProtoReflect.Descriptor instead.
func (*PersonalAccessToken) Descriptor() ([]byte, []int) {
	return file_pkg_proto_pat_proto_rawDescGZIP(), []int{0}
}

func (x *PersonalAccessToken) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PersonalAccessToken) GetTokenableType() EntityType {
	if x != nil {
		return x.TokenableType
	}
	return EntityType_ENTITY_TYPE_UNSPECIFIED
}

func (x *PersonalAccessToken) GetTokenableId() uint64 {
	if x != nil {
		return x.TokenableId
	}
	return 0
}

func (x *PersonalAccessToken) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PersonalAccessToken) GetAbilities() []string {
	if x != nil {
		return x.Abilities
	}
	return nil
}

func (x *PersonalAccessToken) GetLastUsedAt() int64 {
	if x != nil && x.LastUsedAt != nil {
		return *x.LastUsedAt
	}
	return 0
}

func (x *PersonalAccessToken) GetCreatedAt() int64 {
	if x != nil && x.CreatedAt != nil {
		return *x.CreatedAt
	}
	return 0
}

var File_pkg_proto_pat_proto protoreflect.FileDescriptor

const file_pkg_proto_pat_proto_rawDesc = "" +
	"\n" +
	"\x13pkg/proto/pat.proto\x12\x06gameap\x1a\x16pkg/proto/entity.proto\"\xa0\x02\n" +
	"\x13PersonalAccessToken\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x129\n" +
	"\x0etokenable_type\x18\x02 \x01(\x0e2\x12.gameap.EntityTypeR\rtokenableType\x12!\n" +
	"\ftokenable_id\x18\x03 \x01(\x04R\vtokenableId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x1c\n" +
	"\tabilities\x18\x05 \x03(\tR\tabilities\x12%\n" +
	"\flast_used_at\x18\x06 \x01(\x03H\x00R\n" +
	"lastUsedAt\x88\x01\x01\x12\"\n" +
	"\n" +
	"created_at\x18\a \x01(\x03H\x01R\tcreatedAt\x88\x01\x01B\x0f\n" +
	"\r_last_used_atB\r\n" +
	"\v_created_atB$Z\"github.com/gameap/gameap/pkg/protob\x06proto3"

var (
	file_pkg_proto_pat_proto_rawDescOnce sync.Once
	file_pkg_proto_pat_proto_rawDescData []byte
)

func file_pkg_proto_pat_proto_rawDescGZIP() []byte {
	file_pkg_proto_pat_proto_rawDescOnce.Do(func() {
		file_pkg_proto_pat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_pat_proto_rawDesc), len(file_pkg_proto_pat_proto_rawDesc)))
	})
	return file_pkg_proto_pat_proto_rawDescData
}

var file_pkg_proto_pat_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pkg_proto_pat_proto_goTypes = []any{
	(*PersonalAccessToken)(nil), // 0: gameap.PersonalAccessToken
	(EntityType)(0),             // 1: gameap.EntityType
}
var file_pkg_proto_pat_proto_depIdxs = []int32{
	1, // 0: gameap.PersonalAccessToken.tokenable_type:type_name -> gameap.EntityType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_proto_pat_proto_init() }
func file_pkg_proto_pat_proto_init() {
	if File_pkg_proto_pat_proto != nil {
		return
	}
	file_pkg_proto_entity_proto_init()
	file_pkg_proto_pat_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_pat_proto_rawDesc), len(file_pkg_proto_pat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_proto_pat_proto_goTypes,
		DependencyIndexes: file_pkg_proto_pat_proto_depIdxs,
		MessageInfos:      file_pkg_proto_pat_proto_msgTypes,
	}.Build()
	File_pkg_proto_pat_proto = out.File
	file_pkg_proto_pat_proto_goTypes = nil
	file_pkg_proto_pat_proto_depIdxs = nil
}
