// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: pkg/proto/serversetting.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServerSetting struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ServerId      uint64                 `protobuf:"varint,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerSetting) Reset() {
	*x = ServerSetting{}
	mi := &file_pkg_proto_serversetting_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerSetting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerSetting) ProtoMessage() {}

func (x *ServerSetting) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_serversetting_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerSetting.ProtoReflect.Descriptor instead.
func (*ServerSetting) Descriptor() ([]byte, []int) {
	return file_pkg_proto_serversetting_proto_rawDescGZIP(), []int{0}
}

func (x *ServerSetting) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ServerSetting) GetServerId() uint64 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

func (x *ServerSetting) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServerSetting) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_pkg_proto_serversetting_proto protoreflect.FileDescriptor

const file_pkg_proto_serversetting_proto_rawDesc = "" +
	"\n" +
	"\x1dpkg/proto/serversetting.proto\x12\x06gameap\"f\n" +
	"\rServerSetting\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1b\n" +
	"\tserver_id\x18\x02 \x01(\x04R\bserverId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x04 \x01(\tR\x05valueB$Z\"github.com/gameap/gameap/pkg/protob\x06proto3"

var (
	file_pkg_proto_serversetting_proto_rawDescOnce sync.Once
	file_pkg_proto_serversetting_proto_rawDescData []byte
)

func file_pkg_proto_serversetting_proto_rawDescGZIP() []byte {
	file_pkg_proto_serversetting_proto_rawDescOnce.Do(func() {
		file_pkg_proto_serversetting_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_serversetting_proto_rawDesc), len(file_pkg_proto_serversetting_proto_rawDesc)))
	})
	return file_pkg_proto_serversetting_proto_rawDescData
}

var file_pkg_proto_serversetting_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pkg_proto_serversetting_proto_goTypes = []any{
	(*ServerSetting)(nil), // 0: gameap.ServerSetting
}
var file_pkg_proto_serversetting_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_proto_serversetting_proto_init() }
func file_pkg_proto_serversetting_proto_init() {
	if File_pkg_proto_serversetting_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_serversetting_proto_rawDesc), len(file_pkg_proto_serversetting_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_proto_serversetting_proto_goTypes,
		DependencyIndexes: file_pkg_proto_serversetting_proto_depIdxs,
		MessageInfos:      file_pkg_proto_serversetting_proto_msgTypes,
	}.Build()
	File_pkg_proto_serversetting_proto = out.File
	file_pkg_proto_serversetting_proto_goTypes = nil
	file_pkg_proto_serversetting_proto_depIdxs = nil
}
